// DO NOT EDIT
// This package is autogenerated and should not be modified except by the clawc compiler.

package cars

import (
    "fmt"
    "iter"

    "github.com/bearlytools/claw/clawc/languages/go/clawiter"
    "github.com/bearlytools/claw/clawc/languages/go/field"
    "github.com/bearlytools/claw/clawc/languages/go/types/list"
    "github.com/bearlytools/claw/testing/imports/vehicles/claw/manufacturers"
)

// Ensure imports are used.
var _ = fmt.Errorf
var _ = field.FTBool
var _ list.Bools


// IngestWithOptions populates the struct from a token stream with options.
// This is the inverse of Walk().
func (x *Car) IngestWithOptions(tokens iter.Seq[clawiter.Token], opts clawiter.IngestOptions) error {
    ts := clawiter.NewTokenStream(tokens)
    defer ts.Close()
    return x.XXXIngestFrom(ts, opts)
}

// XXXIngestFrom is for internal use - ingests from a shared token stream.
func (x *Car) XXXIngestFrom(ts *clawiter.TokenStream, opts clawiter.IngestOptions) error {
    tok, ok := ts.Next()
    if !ok {
        return fmt.Errorf("expected TokenStructStart, got EOF")
    }
    if tok.Kind != clawiter.TokenStructStart {
        return fmt.Errorf("expected TokenStructStart, got %v", tok.Kind)
    }

    for {
        tok, ok = ts.Next()
        if !ok {
            return fmt.Errorf("unexpected EOF in Car")
        }

        if tok.Kind == clawiter.TokenStructEnd {
            return nil
        }

        if tok.Kind != clawiter.TokenField {
            return fmt.Errorf("expected TokenField, got %v", tok.Kind)
        }

        switch tok.Name {
        case "Manufacturer":
            if len(tok.Bytes) > 0 {
                x.SetManufacturer(manufacturers.ManufacturerByName[tok.String()])
            } else {
                x.SetManufacturer(manufacturers.Manufacturer(tok.Uint8()))
            }
        case "Model":
            if len(tok.Bytes) > 0 {
                x.SetModel(ModelByName[tok.String()])
            } else {
                x.SetModel(Model(tok.Uint8()))
            }
        case "Year":
            x.SetYear(tok.Uint16())
        default:
            if opts.IgnoreUnknownFields {
                if err := clawiter.SkipValue(ts, tok); err != nil {
                    return err
                }
                continue
            }
            return fmt.Errorf("unknown field: %s", tok.Name)
        }
    }
}

