// DO NOT EDIT
// This package is autogenerated and should not be modified except by the clawc compiler.

// Package trucks
package trucks

import (
    "context"
    "io"
    "bytes"
    "fmt"

    "github.com/bearlytools/claw/clawc/languages/go/mapping"
    "github.com/bearlytools/claw/languages/go/reflect"
    "github.com/bearlytools/claw/languages/go/reflect/runtime"
    "github.com/bearlytools/claw/clawc/languages/go/segment"
    "github.com/bearlytools/claw/clawc/languages/go/field"
    
    "github.com/bearlytools/claw/testing/imports/vehicles/claw/manufacturers"
)

// Ensure imports are used.
var (
    _ context.Context
    _ = io.EOF
    _ = bytes.MinRead
    _ = fmt.Errorf
    _ mapping.Map
    _ reflect.StructDescr
    _ = runtime.RegisterPackage
    _ segment.Struct
    _ = field.FTBool
)

// SyntaxVersion is the major version of the Claw language that is being rendered.
const SyntaxVersion = 0

var _package = "trucks"
var _packagePath = "github.com/bearlytools/test_claw_imports/trucks"


type Model uint8

// String implements fmt.Stringer.
func (x Model) String() string {
    return ModelByValue[uint8(x)]
}

// XXXEnumGroup will return the EnumGroup descriptor for this group of enumerators.
// This should only be used by the reflect package and is has no compatibility promises
// like all XXX fields.
func (x Model) XXXEnumGroup() reflect.EnumGroup {
    return XXXEnumGroups.Get(0)
}

// XXXEnumGroup will return the EnumValueDescr descriptor for an enumerated value.
// This should only be used by the reflect package and is has no compatibility promises
// like all XXX fields.
func (x Model) XXXEnumValueDescr() reflect.EnumValueDescr {
    return XXXEnumGroups.Get(0).ByValue(uint16(x))
}
// This is a set of all constants representing enumerated values for enum Model.
const (
    ModelUnknown Model = 0
    F100 Model = 1
    Tundra Model = 2
    Cybertruck Model = 3
)

// ModelByName converts a string representing the enumerator into a Model.
var ModelByName = map[string]Model{
    "Cybertruck": 3,
    "F100": 1,
    "ModelUnknown": 0,
    "Tundra": 2,
}

// ModelByValue converts a uint8 representing a Model into its string name.
var ModelByValue = map[uint8]string{
    0: "ModelUnknown",
    1: "F100",
    2: "Tundra",
    3: "Cybertruck",
}


type Truck struct {
   s *segment.Struct
}

// NewTruck creates a new pooled instance of Truck.
// Call Release() when done to return it to the pool for reuse.
func NewTruck(ctx context.Context) Truck {
    s := segment.New(ctx, XXXMappingTruck)
    return Truck{
        s: s,
    }
}

// Release returns the struct to the pool for reuse.
// After calling Release, the struct should not be used.
func (x Truck) Release(ctx context.Context) {
    x.s.Release(ctx)
}

// XXXNewTruckFrom creates a new Truck from our internal Struct representation.
// As with all things marked XXX*, this should not be used and has not compatibility
// guarantees.
//
// Deprecated: This is not actually deprecated, but it should not be used directly nor
// show up in any documentation.
func XXXNewTruckFrom(s *segment.Struct) Truck {
    return Truck{s: s}
}

// Marshal marshal's the Struct to []byte. The returned slice is shared by Struct,
// so Struct must not be modified after this call. If Struct needs to be modified,
// use MarshalSafe() instead.
func (x Truck) Marshal() ([]byte, error) {
    return x.s.Marshal()
}

// MarshalSafe marshal's the Struct to []byte. The returned slice is a copy
// and safe to modify.
func (x Truck) MarshalSafe() ([]byte, error) {
    return x.s.MarshalSafe()
}

// MarshalWriter marshals to an io.Writer.
func (x Truck) MarshalWriter(w io.Writer) (n int, err error) {
    return x.s.MarshalWriter(w)
}

// Unmarshal unmarshals b into the Struct.
func (x Truck) Unmarshal(b []byte) error {
    return x.s.Unmarshal(b)
}

// UnmarshalReader unmarshals a Struct from an io.Reader.
func (x Truck) UnmarshalReader (r io.Reader) (int, error) {
    return x.s.UnmarshalReader(r)
}

func (x Truck) Manufacturer() manufacturers.Manufacturer {
    return manufacturers.Manufacturer(segment.GetUint8(x.s, 0))
}

func (x Truck) SetManufacturer(value manufacturers.Manufacturer) Truck {
    segment.SetUint8(x.s, 0, uint8(value))
    return x
}

func (x Truck) Model() Model {
    return Model(segment.GetUint8(x.s, 1))
}

func (x Truck) SetModel(value Model) Truck {
    segment.SetUint8(x.s, 1, uint8(value))
    return x
}


func (x Truck) Year() uint16 {
    return segment.GetUint16(x.s, 2)
}

func (x Truck) SetYear(value uint16) Truck {
    segment.SetUint16(x.s, 2, value)
    return x
}



// ClawStruct returns a reflection type representing the Struct.
func (x Truck) ClawStruct() reflect.Struct{
    return reflect.XXXNewStruct(x.s, x.XXXDescr())
}

// XXXGetStruct returns the internal Struct representation. Like all XXX* types/methods,
// this should not be used and has no compatibility guarantees.
//
// Deprecated: Not deprectated, but should not be used and should not show up in documentation.
func (x Truck) XXXGetStruct() *segment.Struct {
    return x.s
}

// SetRecording enables or disables mutation recording for patch generation.
// When enabled, all Set* operations and list mutations are recorded.
func (x Truck) SetRecording(enabled bool) Truck {
    x.s.SetRecording(enabled)
    return x
}

// Recording returns whether mutation recording is enabled.
func (x Truck) Recording() bool {
    return x.s.Recording()
}

// DrainRecordedOps returns all recorded operations since recording was enabled
// (or since the last DrainRecordedOps call) and clears the internal list.
// Use patch.NewPatchFromOps() to convert these to a Patch for application.
func (x Truck) DrainRecordedOps() []segment.RecordedOp {
    return x.s.DrainRecordedOps()
}

// RecordedOpsLen returns the number of recorded operations.
func (x Truck) RecordedOpsLen() int {
    return x.s.RecordedOpsLen()
}

// TruckRaw is a plain Go struct representation of Truck.
// Zero values are not set (sparse encoding).
type TruckRaw struct {
    Manufacturer manufacturers.Manufacturer
    Model Model
    Year uint16
}

// NewTruckFromRaw creates a new Truck from a Raw struct representation.
// Only non-zero values are set (sparse encoding).
func NewTruckFromRaw(ctx context.Context, raw TruckRaw) Truck {
    x := NewTruck(ctx)
    if raw.Manufacturer != 0 {
        x.SetManufacturer(raw.Manufacturer)
    }
    if raw.Model != 0 {
        x.SetModel(raw.Model)
    }
    if raw.Year != 0 {
        x.SetYear(raw.Year)
    }
    return x
}

// ToRaw converts the struct to a plain Go struct representation.
func (x Truck) ToRaw(ctx context.Context) TruckRaw {
    raw := TruckRaw{}
    raw.Manufacturer = x.Manufacturer()
    raw.Model = x.Model()
    raw.Year = x.Year()
    return raw
}
 

// XXXDescr returns the Struct's descriptor. This should only be used
// by the reflect package and is has no compatibility promises like all XXX fields.
//
// Deprecated: No deprecated, but shouldn't be used directly or show up in documentation.
func (x Truck) XXXDescr() reflect.StructDescr {
    return XXXPackageDescr.Structs().Get(0)
} 

// Everything below this line is internal details.
// Deprecated: Not deprecated, but shouldn't be used directly or show up in documentation.
var XXXMappingTruck = &mapping.Map{
    Name: "Truck",
    Pkg: "trucks",
    Path: "github.com/bearlytools/test_claw_imports/trucks",
    Fields: []*mapping.FieldDescr{
        {
            Name: "Manufacturer",
            Type: field.FTUint8,
            Package: "manufacturers",
            FullPath: "github.com/bearlytools/claw/testing/imports/vehicles/claw/manufacturers",
            FieldNum: 0,
            IsEnum: true,
            EnumGroup: "manufacturers.Manufacturer",
        },
        {
            Name: "Model",
            Type: field.FTUint8,
            Package: "trucks",
            FullPath: "github.com/bearlytools/test_claw_imports/trucks",
            FieldNum: 1,
            IsEnum: true,
            EnumGroup: "Model",
        },
        {
            Name: "Year",
            Type: field.FTUint16,
            Package: "trucks",
            FullPath: "github.com/bearlytools/test_claw_imports/trucks",
            FieldNum: 2,
            IsEnum: false,
        },
    },
}


// init initializes all mapping function pointer tables for O(1) dispatch.
func init() {
    XXXMappingTruck.Init()
}




var XXXEnumGroupModel = reflect.XXXEnumGroupImpl{
    GroupName: "Model",
    GroupLen: 4,
    EnumSize: 8,
    Descrs: []reflect.EnumValueDescr{
        reflect.XXXEnumValueDescrImpl{
            EnumName: "ModelUnknown",
            EnumNumber: 0,
            EnumSize: 8,
        },
        reflect.XXXEnumValueDescrImpl{
            EnumName: "F100",
            EnumNumber: 1,
            EnumSize: 8,
        },
        reflect.XXXEnumValueDescrImpl{
            EnumName: "Tundra",
            EnumNumber: 2,
            EnumSize: 8,
        },
        reflect.XXXEnumValueDescrImpl{
            EnumName: "Cybertruck",
            EnumNumber: 3,
            EnumSize: 8,
        },
    },
}

// Deprecated: Not deprecated, but shouldn't be used directly or show up in documentation.
var XXXEnumGroups reflect.EnumGroups = reflect.XXXEnumGroupsImpl{
    List:   []reflect.EnumGroup{
        XXXEnumGroupModel,
    },
    Lookup: map[string]reflect.EnumGroup{
        "Model": XXXEnumGroupModel,
    },
}
 


var XXXStructDescrTruck = &reflect.XXXStructDescrImpl{
    Name:      "Truck",
    Pkg:       XXXMappingTruck.Pkg,
    Path:      XXXMappingTruck.Path,
    Mapping:   XXXMappingTruck,
    FieldList: []reflect.FieldDescr {
        
        reflect.XXXFieldDescrImpl{
            FD: XXXMappingTruck.Fields[0],
            EG: manufacturers.XXXEnumGroupManufacturer,
        },
         
        
        reflect.XXXFieldDescrImpl{
            FD:  XXXMappingTruck.Fields[1],
            EG: XXXEnumGroupModel, 
        }, 
        
        reflect.XXXFieldDescrImpl{
            FD:  XXXMappingTruck.Fields[2],  
        },  
    },
}

var XXXStructDescrs = map[string]*reflect.XXXStructDescrImpl{
    "Truck":  XXXStructDescrTruck,
}

// Deprecated: No deprecated, but shouldn't be used directly or show up in documentation.
var XXXPackageDescr reflect.PackageDescr = &reflect.XXXPackageDescrImpl{
    Name: "trucks",
    Path: "github.com/bearlytools/test_claw_imports/trucks",
    ImportDescrs: []reflect.PackageDescr {
        manufacturers.XXXPackageDescr,
    },
    EnumGroupsDescrs: XXXEnumGroups,
    StructsDescrs: reflect.XXXStructDescrsImpl{
        Descrs: []reflect.StructDescr{
            XXXStructDescrTruck,
        },
    },
}

// PackageDescr returns a PackageDescr for this package.
func PackageDescr() reflect.PackageDescr {
    return XXXPackageDescr
}

// Registers our package description with the runtime.
func init() {
    runtime.RegisterPackage(XXXPackageDescr)
}
