// DO NOT EDIT
// This package is autogenerated and should not be modified except by the clawc compiler.

// Package msgs
package msgs

import (
    "io"
    "bytes"

    "github.com/bearlytools/claw/clawc/languages/go/mapping"
    "github.com/bearlytools/claw/clawc/languages/go/reflect"
    "github.com/bearlytools/claw/clawc/languages/go/reflect/runtime"
    "github.com/bearlytools/claw/clawc/languages/go/structs"
    "github.com/bearlytools/claw/clawc/languages/go/field"
)

// Ensure imports are used.
var (
    _ = io.EOF
    _ = bytes.MinRead
)

// SyntaxVersion is the major version of the Claw language that is being rendered.
const SyntaxVersion = 0

var _package = "msgs"
var _packagePath = "github.com/bearlytools/claw/clawc/languages/patch/msgs"


// OpType defines the type of patch operation.
type OpType uint8

// String implements fmt.Stringer.
func (x OpType) String() string {
    return OpTypeByValue[uint8(x)]
}

// XXXEnumGroup will return the EnumGroup descriptor for this group of enumerators.
// This should only be used by the reflect package and is has no compatibility promises
// like all XXX fields.
func (x OpType) XXXEnumGroup() reflect.EnumGroup {
    return XXXEnumGroups.Get(0)
}

// XXXEnumGroup will return the EnumValueDescr descriptor for an enumerated value.
// This should only be used by the reflect package and is has no compatibility promises
// like all XXX fields.
func (x OpType) XXXEnumValueDescr() reflect.EnumValueDescr {
    return XXXEnumGroups.Get(0).ByValue(uint16(x))
}
// This is a set of all constants representing enumerated values for enum OpType.
const (
    // Unknown is invalid.
    Unknown OpType = 0
    // Set sets a scalar/bytes/string field to a new value.
    Set OpType = 1
    // Clear clears a field (sets to zero value).
    Clear OpType = 2
    // StructPatch applies a nested patch to a struct field.
    StructPatch OpType = 3
    // ListReplace replaces an entire list.
    ListReplace OpType = 4
    // ListSet sets a value at a specific index.
    ListSet OpType = 5
    // ListInsert inserts a value at a specific index.
    ListInsert OpType = 6
    // ListRemove removes a value at a specific index.
    ListRemove OpType = 7
    // ListStructPatch applies a patch to a struct at a list index.
    ListStructPatch OpType = 8
)

// OpTypeByName converts a string representing the enumerator into a OpType.
var OpTypeByName = map[string]OpType{
    "Clear": 2,
    "ListInsert": 6,
    "ListRemove": 7,
    "ListReplace": 4,
    "ListSet": 5,
    "ListStructPatch": 8,
    "Set": 1,
    "StructPatch": 3,
    "Unknown": 0,
}

// OpTypeByValue converts a uint8 representing a OpType into its string name.
var OpTypeByValue = map[uint8]string{
    0: "Unknown",
    1: "Set",
    2: "Clear",
    3: "StructPatch",
    4: "ListReplace",
    5: "ListSet",
    6: "ListInsert",
    7: "ListRemove",
    8: "ListStructPatch",
}


// Op is a single patch operation.
type Op struct {
   s *structs.Struct
}

// NewOp creates a new instance of Op.
func NewOp() Op {
    s := structs.New(0, XXXMappingOp)
    s.XXXSetNoZeroTypeCompression()
    return Op{
        s: s,
    }
}

// XXXNewOpFrom creates a new Op from our internal Struct representation.
// As with all things marked XXX*, this should not be used and has not compatibility
// guarantees.
//
// Deprecated: This is not actually deprecated, but it should not be used directly nor
// show up in any documentation.
func XXXNewOpFrom(s *structs.Struct) Op {
    return Op{s: s}
}

// Marshal marshal's the Struct to []byte. You should consider using MarshalWriter() instead.
func (x Op) Marshal() ([]byte, error) {
    b := bytes.NewBuffer(make([]byte, 0, int(structs.XXXGetStructTotal(x.s))))
    _, err := x.s.Marshal(b)
    if err != nil {
        return nil, err
    }
    return b.Bytes(), nil
}

// MarshalWriter marshals to an io.Writer.
func (x Op) MarshalWriter(w io.Writer) (n int, err error) {
    return x.s.Marshal(w)
}

// Unmarshal unmarshals b into the Struct.
func (x Op) Unmarshal(b []byte) error {
    buff := bytes.NewBuffer(b)
    _, err := x.s.Unmarshal(buff)
    return err
}

// UnmarshalReader unmarshals a Struct from an io.Reader.
func (x Op) UnmarshalReader (r io.Reader) (int, error) {
    return x.s.Unmarshal(r)
}

// FieldNum is the field number this operation applies to.

func (x Op) FieldNum() uint16 {
    return structs.MustGetNumber[uint16](x.s, 0)
}

func (x Op) SetFieldNum(value uint16) Op {
    structs.MustSetNumber(x.s, 0, value)
    return x
}

// Type is the operation type.
func (x Op) Type() OpType {
    return OpType(structs.MustGetNumber[uint8](x.s, 1))
}

func (x Op) SetType(value OpType) Op {
    structs.MustSetNumber(x.s, 1, uint8(value))
    return x
}

// Index is the list index (for list operations, -1 otherwise).
func (x Op) Index() int32 {
    return structs.MustGetNumber[int32](x.s, 2)
}

func (x Op) SetIndex(value int32) Op {
    structs.MustSetNumber(x.s, 2, value)
    return x
}

// Data is the encoded payload (value, nested patch, etc.).
func (x Op) Data() []byte {
    ptr := structs.MustGetBytes(x.s, 3)
    if ptr == nil {
        return nil
    }
    return *ptr
}

func (x Op) SafeGetData() []byte {
    ptr := structs.MustGetBytes(x.s, 3)
    if ptr == nil {
        return nil
    }
    b := make([]byte, len(*ptr))
    copy(b, *ptr)
    return b
}

func (x Op) SetData(value []byte) Op {
    structs.MustSetBytes(x.s, 3, value, false)
    return x
}



// ClawStruct returns a reflection type representing the Struct.
func (x Op) ClawStruct() reflect.Struct{
    descr := XXXStructDescrOp
    return reflect.XXXNewStruct(x.s, descr)
}

// XXXGetStruct returns the internal Struct representation. Like all XXX* types/methods,
// this should not be used and has no compatibility guarantees.
//
// Deprecated: Not deprectated, but should not be used and should not show up in documentation.
func (x Op) XXXGetStruct() *structs.Struct {
    return x.s
} 

// XXXDescr returns the Struct's descriptor. This should only be used
// by the reflect package and is has no compatibility promises like all XXX fields.
//
// Deprecated: No deprecated, but shouldn't be used directly or show up in documentation.
func (x Op) XXXDescr() reflect.StructDescr {
    return XXXPackageDescr.Structs().Get(0)
}

// Patch represents a diff between two structs.
type Patch struct {
   s *structs.Struct
}

// NewPatch creates a new instance of Patch.
func NewPatch() Patch {
    s := structs.New(0, XXXMappingPatch)
    s.XXXSetNoZeroTypeCompression()
    return Patch{
        s: s,
    }
}

// XXXNewPatchFrom creates a new Patch from our internal Struct representation.
// As with all things marked XXX*, this should not be used and has not compatibility
// guarantees.
//
// Deprecated: This is not actually deprecated, but it should not be used directly nor
// show up in any documentation.
func XXXNewPatchFrom(s *structs.Struct) Patch {
    return Patch{s: s}
}

// Marshal marshal's the Struct to []byte. You should consider using MarshalWriter() instead.
func (x Patch) Marshal() ([]byte, error) {
    b := bytes.NewBuffer(make([]byte, 0, int(structs.XXXGetStructTotal(x.s))))
    _, err := x.s.Marshal(b)
    if err != nil {
        return nil, err
    }
    return b.Bytes(), nil
}

// MarshalWriter marshals to an io.Writer.
func (x Patch) MarshalWriter(w io.Writer) (n int, err error) {
    return x.s.Marshal(w)
}

// Unmarshal unmarshals b into the Struct.
func (x Patch) Unmarshal(b []byte) error {
    buff := bytes.NewBuffer(b)
    _, err := x.s.Unmarshal(buff)
    return err
}

// UnmarshalReader unmarshals a Struct from an io.Reader.
func (x Patch) UnmarshalReader (r io.Reader) (int, error) {
    return x.s.Unmarshal(r)
}

// Version is the patch format version.

func (x Patch) Version() uint8 {
    return structs.MustGetNumber[uint8](x.s, 0)
}

func (x Patch) SetVersion(value uint8) Patch {
    structs.MustSetNumber(x.s, 0, value)
    return x
}

// Ops is the list of operations to apply.
func (x Patch) Ops() []Op {
    l := structs.MustGetListStruct(x.s, 1)
    if l == nil {
        return nil
    }
    vals := make([]Op, l.Len())

    for i := range vals {
        vals[i] = Op{s: l.Get(i)}
    }
    return vals
}

func (x Patch) AppendOps(values ...Op) {
    vals := make([]*structs.Struct, len(values))
    for i, val := range values {
        vals[i] = val.XXXGetStruct()
    }
    structs.MustAppendListStruct(x.s, 1, vals...)
}


// ClawStruct returns a reflection type representing the Struct.
func (x Patch) ClawStruct() reflect.Struct{
    descr := XXXStructDescrPatch
    return reflect.XXXNewStruct(x.s, descr)
}

// XXXGetStruct returns the internal Struct representation. Like all XXX* types/methods,
// this should not be used and has no compatibility guarantees.
//
// Deprecated: Not deprectated, but should not be used and should not show up in documentation.
func (x Patch) XXXGetStruct() *structs.Struct {
    return x.s
} 

// XXXDescr returns the Struct's descriptor. This should only be used
// by the reflect package and is has no compatibility promises like all XXX fields.
//
// Deprecated: No deprecated, but shouldn't be used directly or show up in documentation.
func (x Patch) XXXDescr() reflect.StructDescr {
    return XXXPackageDescr.Structs().Get(1)
} 

// Everything below this line is internal details.
// Deprecated: Not deprecated, but shouldn't be used directly or show up in documentation.
var XXXMappingOp = &mapping.Map{
    Name: "Op",
    Pkg: "msgs",
    Path: "github.com/bearlytools/claw/clawc/languages/patch/msgs",
    Fields: []*mapping.FieldDescr{
        {
            Name: "FieldNum",
            Type: field.FTUint16,
            Package: "msgs",
            FullPath: "github.com/bearlytools/claw/clawc/languages/patch/msgs",
            FieldNum: 0,
            IsEnum: false,
        },
        {
            Name: "Type",
            Type: field.FTUint8,
            Package: "msgs",
            FullPath: "github.com/bearlytools/claw/clawc/languages/patch/msgs",
            FieldNum: 1,
            IsEnum: true,
            EnumGroup: "OpType",
        },
        {
            Name: "Index",
            Type: field.FTInt32,
            Package: "msgs",
            FullPath: "github.com/bearlytools/claw/clawc/languages/patch/msgs",
            FieldNum: 2,
            IsEnum: false,
        },
        {
            Name: "Data",
            Type: field.FTBytes,
            Package: "msgs",
            FullPath: "github.com/bearlytools/claw/clawc/languages/patch/msgs",
            FieldNum: 3,
            IsEnum: false,
        },
    },
}

// Deprecated: Not deprecated, but shouldn't be used directly or show up in documentation.
var XXXMappingPatch = &mapping.Map{
    Name: "Patch",
    Pkg: "msgs",
    Path: "github.com/bearlytools/claw/clawc/languages/patch/msgs",
    Fields: []*mapping.FieldDescr{
        {
            Name: "Version",
            Type: field.FTUint8,
            Package: "msgs",
            FullPath: "github.com/bearlytools/claw/clawc/languages/patch/msgs",
            FieldNum: 0,
            IsEnum: false,
        },
        {
            Name: "Ops",
            Type: field.FTListStructs,
            Package: "msgs",
            FullPath: "github.com/bearlytools/claw/clawc/languages/patch/msgs",
            FieldNum: 1,
            IsEnum: false,
            
            Mapping: XXXMappingOp,
        },
    },
}


// init initializes all mapping function pointer tables for O(1) dispatch.
func init() {
    XXXMappingOp.Init()
    XXXMappingPatch.Init()
}




var XXXEnumGroupOpType = reflect.XXXEnumGroupImpl{
    GroupName: "OpType",
    GroupLen: 9,
    EnumSize: 8,
    Descrs: []reflect.EnumValueDescr{
        reflect.XXXEnumValueDescrImpl{
            EnumName: "Unknown",
            EnumNumber: 0,
            EnumSize: 8,
        },
        reflect.XXXEnumValueDescrImpl{
            EnumName: "Set",
            EnumNumber: 1,
            EnumSize: 8,
        },
        reflect.XXXEnumValueDescrImpl{
            EnumName: "Clear",
            EnumNumber: 2,
            EnumSize: 8,
        },
        reflect.XXXEnumValueDescrImpl{
            EnumName: "StructPatch",
            EnumNumber: 3,
            EnumSize: 8,
        },
        reflect.XXXEnumValueDescrImpl{
            EnumName: "ListReplace",
            EnumNumber: 4,
            EnumSize: 8,
        },
        reflect.XXXEnumValueDescrImpl{
            EnumName: "ListSet",
            EnumNumber: 5,
            EnumSize: 8,
        },
        reflect.XXXEnumValueDescrImpl{
            EnumName: "ListInsert",
            EnumNumber: 6,
            EnumSize: 8,
        },
        reflect.XXXEnumValueDescrImpl{
            EnumName: "ListRemove",
            EnumNumber: 7,
            EnumSize: 8,
        },
        reflect.XXXEnumValueDescrImpl{
            EnumName: "ListStructPatch",
            EnumNumber: 8,
            EnumSize: 8,
        },
    },
}

// Deprecated: Not deprecated, but shouldn't be used directly or show up in documentation.
var XXXEnumGroups reflect.EnumGroups = reflect.XXXEnumGroupsImpl{
    List:   []reflect.EnumGroup{
        XXXEnumGroupOpType,
    },
    Lookup: map[string]reflect.EnumGroup{
        "OpType": XXXEnumGroupOpType,
    },
}
 


var XXXStructDescrOp = &reflect.XXXStructDescrImpl{
    Name:      "Op",
    Pkg:       XXXMappingOp.Pkg,
    Path:      XXXMappingOp.Path,
    Mapping:   XXXMappingOp,
    FieldList: []reflect.FieldDescr {
        
        reflect.XXXFieldDescrImpl{
            FD:  XXXMappingOp.Fields[0],  
        }, 
        
        reflect.XXXFieldDescrImpl{
            FD:  XXXMappingOp.Fields[1],
            EG: XXXEnumGroupOpType, 
        }, 
        
        reflect.XXXFieldDescrImpl{
            FD:  XXXMappingOp.Fields[2],  
        }, 
        
        reflect.XXXFieldDescrImpl{
            FD:  XXXMappingOp.Fields[3],  
        },  
    },
}

var XXXStructDescrPatch = &reflect.XXXStructDescrImpl{
    Name:      "Patch",
    Pkg:       XXXMappingPatch.Pkg,
    Path:      XXXMappingPatch.Path,
    Mapping:   XXXMappingPatch,
    FieldList: []reflect.FieldDescr {
        
        reflect.XXXFieldDescrImpl{
            FD:  XXXMappingPatch.Fields[0],  
        }, 
        
        reflect.XXXFieldDescrImpl{
            FD:  XXXMappingPatch.Fields[1],
            SD: XXXStructDescrOp,  
        },  
    },
}

var XXXStructDescrs = map[string]*reflect.XXXStructDescrImpl{
    "Op":  XXXStructDescrOp,
    "Patch":  XXXStructDescrPatch,
}

// Deprecated: No deprecated, but shouldn't be used directly or show up in documentation.
var XXXPackageDescr reflect.PackageDescr = &reflect.XXXPackageDescrImpl{
    Name: "msgs",
    Path: "github.com/bearlytools/claw/clawc/languages/patch/msgs",
    EnumGroupsDescrs: XXXEnumGroups,
    StructsDescrs: reflect.XXXStructDescrsImpl{
        Descrs: []reflect.StructDescr{
            XXXStructDescrPatch,
            XXXStructDescrOp,
        },
    },
}

// PackageDescr returns a PackageDescr for this package.
func PackageDescr() reflect.PackageDescr {
    return XXXPackageDescr
}

// Registers our package description with the runtime.
func init() {
    runtime.RegisterPackage(XXXPackageDescr)
}
