// DO NOT EDIT
// This package is autogenerated and should not be modified except by the clawc compiler.

// Package reflection
package reflection

import (
    "context"
    "io"
    "bytes"
    "fmt"

    "github.com/bearlytools/claw/clawc/languages/go/mapping"
    "github.com/bearlytools/claw/languages/go/reflect"
    "github.com/bearlytools/claw/languages/go/reflect/runtime"
    "github.com/bearlytools/claw/clawc/languages/go/segment"
    "github.com/bearlytools/claw/clawc/languages/go/field"
    
    "github.com/bearlytools/claw/rpc/internal/msgs"
)

// Ensure imports are used.
var (
    _ context.Context
    _ = io.EOF
    _ = bytes.MinRead
    _ = fmt.Errorf
    _ mapping.Map
    _ reflect.StructDescr
    _ = runtime.RegisterPackage
    _ segment.Struct
    _ = field.FTBool
)

// SyntaxVersion is the major version of the Claw language that is being rendered.
const SyntaxVersion = 0

var _package = "reflection"
var _packagePath = "github.com/bearlytools/claw/rpc/reflection"




// GetMethodInfoRequest is the request for getting info about a specific method.
type GetMethodInfoRequest struct {
   s *segment.Struct
}

// NewGetMethodInfoRequest creates a new pooled instance of GetMethodInfoRequest.
// Call Release() when done to return it to the pool for reuse.
func NewGetMethodInfoRequest(ctx context.Context) GetMethodInfoRequest {
    s := segment.New(ctx, XXXMappingGetMethodInfoRequest)
    return GetMethodInfoRequest{
        s: s,
    }
}

// Release returns the struct to the pool for reuse.
// After calling Release, the struct should not be used.
func (x GetMethodInfoRequest) Release(ctx context.Context) {
    x.s.Release(ctx)
}

// XXXNewGetMethodInfoRequestFrom creates a new GetMethodInfoRequest from our internal Struct representation.
// As with all things marked XXX*, this should not be used and has not compatibility
// guarantees.
//
// Deprecated: This is not actually deprecated, but it should not be used directly nor
// show up in any documentation.
func XXXNewGetMethodInfoRequestFrom(s *segment.Struct) GetMethodInfoRequest {
    return GetMethodInfoRequest{s: s}
}

// Marshal marshal's the Struct to []byte. The returned slice is shared by Struct,
// so Struct must not be modified after this call. If Struct needs to be modified,
// use MarshalSafe() instead.
func (x GetMethodInfoRequest) Marshal() ([]byte, error) {
    return x.s.Marshal()
}

// MarshalSafe marshal's the Struct to []byte. The returned slice is a copy
// and safe to modify.
func (x GetMethodInfoRequest) MarshalSafe() ([]byte, error) {
    return x.s.MarshalSafe()
}

// MarshalWriter marshals to an io.Writer.
func (x GetMethodInfoRequest) MarshalWriter(w io.Writer) (n int, err error) {
    return x.s.MarshalWriter(w)
}

// Unmarshal unmarshals b into the Struct.
func (x GetMethodInfoRequest) Unmarshal(b []byte) error {
    return x.s.Unmarshal(b)
}

// UnmarshalReader unmarshals a Struct from an io.Reader.
func (x GetMethodInfoRequest) UnmarshalReader (r io.Reader) (int, error) {
    return x.s.UnmarshalReader(r)
}

// Package is the package name.
func (x GetMethodInfoRequest) Package() string {
    return segment.GetString(x.s, 0)
}

func (x GetMethodInfoRequest) SetPackage(value string) GetMethodInfoRequest {
    segment.SetString(x.s, 0, value)
    return x
}

// Service is the service name.
func (x GetMethodInfoRequest) Service() string {
    return segment.GetString(x.s, 1)
}

func (x GetMethodInfoRequest) SetService(value string) GetMethodInfoRequest {
    segment.SetString(x.s, 1, value)
    return x
}

// Method is the method name.
func (x GetMethodInfoRequest) Method() string {
    return segment.GetString(x.s, 2)
}

func (x GetMethodInfoRequest) SetMethod(value string) GetMethodInfoRequest {
    segment.SetString(x.s, 2, value)
    return x
}



// ClawStruct returns a reflection type representing the Struct.
func (x GetMethodInfoRequest) ClawStruct() reflect.Struct{
    return reflect.XXXNewStruct(x.s, x.XXXDescr())
}

// XXXGetStruct returns the internal Struct representation. Like all XXX* types/methods,
// this should not be used and has no compatibility guarantees.
//
// Deprecated: Not deprectated, but should not be used and should not show up in documentation.
func (x GetMethodInfoRequest) XXXGetStruct() *segment.Struct {
    return x.s
}

// XXXTypeHash returns the SHAKE128 hash (128 bits) of this type's identity.
// Used for Any type serialization to identify the concrete type.
//
// Deprecated: Not deprecated, but should not be used directly and should not show up in documentation.
func (x GetMethodInfoRequest) XXXTypeHash() [16]byte {
    return XXXTypeHashGetMethodInfoRequest
}

// SetRecording enables or disables mutation recording for patch generation.
// When enabled, all Set* operations and list mutations are recorded.
func (x GetMethodInfoRequest) SetRecording(enabled bool) GetMethodInfoRequest {
    x.s.SetRecording(enabled)
    return x
}

// Recording returns whether mutation recording is enabled.
func (x GetMethodInfoRequest) Recording() bool {
    return x.s.Recording()
}

// DrainRecordedOps returns all recorded operations since recording was enabled
// (or since the last DrainRecordedOps call) and clears the internal list.
// Use patch.NewPatchFromOps() to convert these to a Patch for application.
func (x GetMethodInfoRequest) DrainRecordedOps() []segment.RecordedOp {
    return x.s.DrainRecordedOps()
}

// RecordedOpsLen returns the number of recorded operations.
func (x GetMethodInfoRequest) RecordedOpsLen() int {
    return x.s.RecordedOpsLen()
}

// GetMethodInfoRequestRaw is a plain Go struct representation of GetMethodInfoRequest.
// Zero values are not set (sparse encoding).
type GetMethodInfoRequestRaw struct {
    Package string
    Service string
    Method string
}

// NewGetMethodInfoRequestFromRaw creates a new GetMethodInfoRequest from a Raw struct representation.
// Only non-zero values are set (sparse encoding).
func NewGetMethodInfoRequestFromRaw(ctx context.Context, raw GetMethodInfoRequestRaw) GetMethodInfoRequest {
    x := NewGetMethodInfoRequest(ctx)
    if raw.Package != "" {
        x.SetPackage(raw.Package)
    }
    if raw.Service != "" {
        x.SetService(raw.Service)
    }
    if raw.Method != "" {
        x.SetMethod(raw.Method)
    }
    return x
}

// ToRaw converts the struct to a plain Go struct representation.
func (x GetMethodInfoRequest) ToRaw(ctx context.Context) GetMethodInfoRequestRaw {
    raw := GetMethodInfoRequestRaw{}
    raw.Package = x.Package()
    raw.Service = x.Service()
    raw.Method = x.Method()
    return raw
}
 

// XXXDescr returns the Struct's descriptor. This should only be used
// by the reflect package and is has no compatibility promises like all XXX fields.
//
// Deprecated: No deprecated, but shouldn't be used directly or show up in documentation.
func (x GetMethodInfoRequest) XXXDescr() reflect.StructDescr {
    return XXXPackageDescr.Structs().Get(0)
}

// GetMethodInfoResponse is the response with method information.
type GetMethodInfoResponse struct {
   s *segment.Struct
}

// NewGetMethodInfoResponse creates a new pooled instance of GetMethodInfoResponse.
// Call Release() when done to return it to the pool for reuse.
func NewGetMethodInfoResponse(ctx context.Context) GetMethodInfoResponse {
    s := segment.New(ctx, XXXMappingGetMethodInfoResponse)
    return GetMethodInfoResponse{
        s: s,
    }
}

// Release returns the struct to the pool for reuse.
// After calling Release, the struct should not be used.
func (x GetMethodInfoResponse) Release(ctx context.Context) {
    x.s.Release(ctx)
}

// XXXNewGetMethodInfoResponseFrom creates a new GetMethodInfoResponse from our internal Struct representation.
// As with all things marked XXX*, this should not be used and has not compatibility
// guarantees.
//
// Deprecated: This is not actually deprecated, but it should not be used directly nor
// show up in any documentation.
func XXXNewGetMethodInfoResponseFrom(s *segment.Struct) GetMethodInfoResponse {
    return GetMethodInfoResponse{s: s}
}

// Marshal marshal's the Struct to []byte. The returned slice is shared by Struct,
// so Struct must not be modified after this call. If Struct needs to be modified,
// use MarshalSafe() instead.
func (x GetMethodInfoResponse) Marshal() ([]byte, error) {
    return x.s.Marshal()
}

// MarshalSafe marshal's the Struct to []byte. The returned slice is a copy
// and safe to modify.
func (x GetMethodInfoResponse) MarshalSafe() ([]byte, error) {
    return x.s.MarshalSafe()
}

// MarshalWriter marshals to an io.Writer.
func (x GetMethodInfoResponse) MarshalWriter(w io.Writer) (n int, err error) {
    return x.s.MarshalWriter(w)
}

// Unmarshal unmarshals b into the Struct.
func (x GetMethodInfoResponse) Unmarshal(b []byte) error {
    return x.s.Unmarshal(b)
}

// UnmarshalReader unmarshals a Struct from an io.Reader.
func (x GetMethodInfoResponse) UnmarshalReader (r io.Reader) (int, error) {
    return x.s.UnmarshalReader(r)
}

// Method is the method information.
func (x GetMethodInfoResponse) Method() MethodInfo {
    s := segment.GetNestedStruct(x.s, 0, XXXMappingMethodInfo)
    return MethodInfo{s: s}
}

func (x GetMethodInfoResponse) SetMethod(value MethodInfo) GetMethodInfoResponse {
    segment.SetNestedStruct(x.s, 0, value.XXXGetStruct())
    return x
}

// Found indicates whether the method was found.
func (x GetMethodInfoResponse) Found() bool {
    return segment.GetBool(x.s, 1)
}

func (x GetMethodInfoResponse) SetFound(value bool) GetMethodInfoResponse {
    segment.SetBool(x.s, 1, value)
    return x
}



// ClawStruct returns a reflection type representing the Struct.
func (x GetMethodInfoResponse) ClawStruct() reflect.Struct{
    return reflect.XXXNewStruct(x.s, x.XXXDescr())
}

// XXXGetStruct returns the internal Struct representation. Like all XXX* types/methods,
// this should not be used and has no compatibility guarantees.
//
// Deprecated: Not deprectated, but should not be used and should not show up in documentation.
func (x GetMethodInfoResponse) XXXGetStruct() *segment.Struct {
    return x.s
}

// XXXTypeHash returns the SHAKE128 hash (128 bits) of this type's identity.
// Used for Any type serialization to identify the concrete type.
//
// Deprecated: Not deprecated, but should not be used directly and should not show up in documentation.
func (x GetMethodInfoResponse) XXXTypeHash() [16]byte {
    return XXXTypeHashGetMethodInfoResponse
}

// SetRecording enables or disables mutation recording for patch generation.
// When enabled, all Set* operations and list mutations are recorded.
func (x GetMethodInfoResponse) SetRecording(enabled bool) GetMethodInfoResponse {
    x.s.SetRecording(enabled)
    return x
}

// Recording returns whether mutation recording is enabled.
func (x GetMethodInfoResponse) Recording() bool {
    return x.s.Recording()
}

// DrainRecordedOps returns all recorded operations since recording was enabled
// (or since the last DrainRecordedOps call) and clears the internal list.
// Use patch.NewPatchFromOps() to convert these to a Patch for application.
func (x GetMethodInfoResponse) DrainRecordedOps() []segment.RecordedOp {
    return x.s.DrainRecordedOps()
}

// RecordedOpsLen returns the number of recorded operations.
func (x GetMethodInfoResponse) RecordedOpsLen() int {
    return x.s.RecordedOpsLen()
}

// GetMethodInfoResponseRaw is a plain Go struct representation of GetMethodInfoResponse.
// Zero values are not set (sparse encoding).
type GetMethodInfoResponseRaw struct {
    Method *MethodInfoRaw
    Found bool
}

// NewGetMethodInfoResponseFromRaw creates a new GetMethodInfoResponse from a Raw struct representation.
// Only non-zero values are set (sparse encoding).
func NewGetMethodInfoResponseFromRaw(ctx context.Context, raw GetMethodInfoResponseRaw) GetMethodInfoResponse {
    x := NewGetMethodInfoResponse(ctx)
    if raw.Method != nil {
        x.SetMethod(NewMethodInfoFromRaw(ctx, *raw.Method))
    }
    if raw.Found {
        x.SetFound(raw.Found)
    }
    return x
}

// ToRaw converts the struct to a plain Go struct representation.
func (x GetMethodInfoResponse) ToRaw(ctx context.Context) GetMethodInfoResponseRaw {
    raw := GetMethodInfoResponseRaw{}
    if x.s.HasField(0) {
        nestedRaw := x.Method().ToRaw(ctx)
        raw.Method = &nestedRaw
    }
    raw.Found = x.Found()
    return raw
}
 

// XXXDescr returns the Struct's descriptor. This should only be used
// by the reflect package and is has no compatibility promises like all XXX fields.
//
// Deprecated: No deprecated, but shouldn't be used directly or show up in documentation.
func (x GetMethodInfoResponse) XXXDescr() reflect.StructDescr {
    return XXXPackageDescr.Structs().Get(1)
}

// GetServiceInfoRequest is the request for getting info about a specific service.
type GetServiceInfoRequest struct {
   s *segment.Struct
}

// NewGetServiceInfoRequest creates a new pooled instance of GetServiceInfoRequest.
// Call Release() when done to return it to the pool for reuse.
func NewGetServiceInfoRequest(ctx context.Context) GetServiceInfoRequest {
    s := segment.New(ctx, XXXMappingGetServiceInfoRequest)
    return GetServiceInfoRequest{
        s: s,
    }
}

// Release returns the struct to the pool for reuse.
// After calling Release, the struct should not be used.
func (x GetServiceInfoRequest) Release(ctx context.Context) {
    x.s.Release(ctx)
}

// XXXNewGetServiceInfoRequestFrom creates a new GetServiceInfoRequest from our internal Struct representation.
// As with all things marked XXX*, this should not be used and has not compatibility
// guarantees.
//
// Deprecated: This is not actually deprecated, but it should not be used directly nor
// show up in any documentation.
func XXXNewGetServiceInfoRequestFrom(s *segment.Struct) GetServiceInfoRequest {
    return GetServiceInfoRequest{s: s}
}

// Marshal marshal's the Struct to []byte. The returned slice is shared by Struct,
// so Struct must not be modified after this call. If Struct needs to be modified,
// use MarshalSafe() instead.
func (x GetServiceInfoRequest) Marshal() ([]byte, error) {
    return x.s.Marshal()
}

// MarshalSafe marshal's the Struct to []byte. The returned slice is a copy
// and safe to modify.
func (x GetServiceInfoRequest) MarshalSafe() ([]byte, error) {
    return x.s.MarshalSafe()
}

// MarshalWriter marshals to an io.Writer.
func (x GetServiceInfoRequest) MarshalWriter(w io.Writer) (n int, err error) {
    return x.s.MarshalWriter(w)
}

// Unmarshal unmarshals b into the Struct.
func (x GetServiceInfoRequest) Unmarshal(b []byte) error {
    return x.s.Unmarshal(b)
}

// UnmarshalReader unmarshals a Struct from an io.Reader.
func (x GetServiceInfoRequest) UnmarshalReader (r io.Reader) (int, error) {
    return x.s.UnmarshalReader(r)
}

// Package is the package name.
func (x GetServiceInfoRequest) Package() string {
    return segment.GetString(x.s, 0)
}

func (x GetServiceInfoRequest) SetPackage(value string) GetServiceInfoRequest {
    segment.SetString(x.s, 0, value)
    return x
}

// Service is the service name.
func (x GetServiceInfoRequest) Service() string {
    return segment.GetString(x.s, 1)
}

func (x GetServiceInfoRequest) SetService(value string) GetServiceInfoRequest {
    segment.SetString(x.s, 1, value)
    return x
}



// ClawStruct returns a reflection type representing the Struct.
func (x GetServiceInfoRequest) ClawStruct() reflect.Struct{
    return reflect.XXXNewStruct(x.s, x.XXXDescr())
}

// XXXGetStruct returns the internal Struct representation. Like all XXX* types/methods,
// this should not be used and has no compatibility guarantees.
//
// Deprecated: Not deprectated, but should not be used and should not show up in documentation.
func (x GetServiceInfoRequest) XXXGetStruct() *segment.Struct {
    return x.s
}

// XXXTypeHash returns the SHAKE128 hash (128 bits) of this type's identity.
// Used for Any type serialization to identify the concrete type.
//
// Deprecated: Not deprecated, but should not be used directly and should not show up in documentation.
func (x GetServiceInfoRequest) XXXTypeHash() [16]byte {
    return XXXTypeHashGetServiceInfoRequest
}

// SetRecording enables or disables mutation recording for patch generation.
// When enabled, all Set* operations and list mutations are recorded.
func (x GetServiceInfoRequest) SetRecording(enabled bool) GetServiceInfoRequest {
    x.s.SetRecording(enabled)
    return x
}

// Recording returns whether mutation recording is enabled.
func (x GetServiceInfoRequest) Recording() bool {
    return x.s.Recording()
}

// DrainRecordedOps returns all recorded operations since recording was enabled
// (or since the last DrainRecordedOps call) and clears the internal list.
// Use patch.NewPatchFromOps() to convert these to a Patch for application.
func (x GetServiceInfoRequest) DrainRecordedOps() []segment.RecordedOp {
    return x.s.DrainRecordedOps()
}

// RecordedOpsLen returns the number of recorded operations.
func (x GetServiceInfoRequest) RecordedOpsLen() int {
    return x.s.RecordedOpsLen()
}

// GetServiceInfoRequestRaw is a plain Go struct representation of GetServiceInfoRequest.
// Zero values are not set (sparse encoding).
type GetServiceInfoRequestRaw struct {
    Package string
    Service string
}

// NewGetServiceInfoRequestFromRaw creates a new GetServiceInfoRequest from a Raw struct representation.
// Only non-zero values are set (sparse encoding).
func NewGetServiceInfoRequestFromRaw(ctx context.Context, raw GetServiceInfoRequestRaw) GetServiceInfoRequest {
    x := NewGetServiceInfoRequest(ctx)
    if raw.Package != "" {
        x.SetPackage(raw.Package)
    }
    if raw.Service != "" {
        x.SetService(raw.Service)
    }
    return x
}

// ToRaw converts the struct to a plain Go struct representation.
func (x GetServiceInfoRequest) ToRaw(ctx context.Context) GetServiceInfoRequestRaw {
    raw := GetServiceInfoRequestRaw{}
    raw.Package = x.Package()
    raw.Service = x.Service()
    return raw
}
 

// XXXDescr returns the Struct's descriptor. This should only be used
// by the reflect package and is has no compatibility promises like all XXX fields.
//
// Deprecated: No deprecated, but shouldn't be used directly or show up in documentation.
func (x GetServiceInfoRequest) XXXDescr() reflect.StructDescr {
    return XXXPackageDescr.Structs().Get(2)
}

// GetServiceInfoResponse is the response with service information.
type GetServiceInfoResponse struct {
   s *segment.Struct
}

// NewGetServiceInfoResponse creates a new pooled instance of GetServiceInfoResponse.
// Call Release() when done to return it to the pool for reuse.
func NewGetServiceInfoResponse(ctx context.Context) GetServiceInfoResponse {
    s := segment.New(ctx, XXXMappingGetServiceInfoResponse)
    return GetServiceInfoResponse{
        s: s,
    }
}

// Release returns the struct to the pool for reuse.
// After calling Release, the struct should not be used.
func (x GetServiceInfoResponse) Release(ctx context.Context) {
    x.s.Release(ctx)
}

// XXXNewGetServiceInfoResponseFrom creates a new GetServiceInfoResponse from our internal Struct representation.
// As with all things marked XXX*, this should not be used and has not compatibility
// guarantees.
//
// Deprecated: This is not actually deprecated, but it should not be used directly nor
// show up in any documentation.
func XXXNewGetServiceInfoResponseFrom(s *segment.Struct) GetServiceInfoResponse {
    return GetServiceInfoResponse{s: s}
}

// Marshal marshal's the Struct to []byte. The returned slice is shared by Struct,
// so Struct must not be modified after this call. If Struct needs to be modified,
// use MarshalSafe() instead.
func (x GetServiceInfoResponse) Marshal() ([]byte, error) {
    return x.s.Marshal()
}

// MarshalSafe marshal's the Struct to []byte. The returned slice is a copy
// and safe to modify.
func (x GetServiceInfoResponse) MarshalSafe() ([]byte, error) {
    return x.s.MarshalSafe()
}

// MarshalWriter marshals to an io.Writer.
func (x GetServiceInfoResponse) MarshalWriter(w io.Writer) (n int, err error) {
    return x.s.MarshalWriter(w)
}

// Unmarshal unmarshals b into the Struct.
func (x GetServiceInfoResponse) Unmarshal(b []byte) error {
    return x.s.Unmarshal(b)
}

// UnmarshalReader unmarshals a Struct from an io.Reader.
func (x GetServiceInfoResponse) UnmarshalReader (r io.Reader) (int, error) {
    return x.s.UnmarshalReader(r)
}

// Service is the service information.
func (x GetServiceInfoResponse) Service() ServiceInfo {
    s := segment.GetNestedStruct(x.s, 0, XXXMappingServiceInfo)
    return ServiceInfo{s: s}
}

func (x GetServiceInfoResponse) SetService(value ServiceInfo) GetServiceInfoResponse {
    segment.SetNestedStruct(x.s, 0, value.XXXGetStruct())
    return x
}

// Found indicates whether the service was found.
func (x GetServiceInfoResponse) Found() bool {
    return segment.GetBool(x.s, 1)
}

func (x GetServiceInfoResponse) SetFound(value bool) GetServiceInfoResponse {
    segment.SetBool(x.s, 1, value)
    return x
}



// ClawStruct returns a reflection type representing the Struct.
func (x GetServiceInfoResponse) ClawStruct() reflect.Struct{
    return reflect.XXXNewStruct(x.s, x.XXXDescr())
}

// XXXGetStruct returns the internal Struct representation. Like all XXX* types/methods,
// this should not be used and has no compatibility guarantees.
//
// Deprecated: Not deprectated, but should not be used and should not show up in documentation.
func (x GetServiceInfoResponse) XXXGetStruct() *segment.Struct {
    return x.s
}

// XXXTypeHash returns the SHAKE128 hash (128 bits) of this type's identity.
// Used for Any type serialization to identify the concrete type.
//
// Deprecated: Not deprecated, but should not be used directly and should not show up in documentation.
func (x GetServiceInfoResponse) XXXTypeHash() [16]byte {
    return XXXTypeHashGetServiceInfoResponse
}

// SetRecording enables or disables mutation recording for patch generation.
// When enabled, all Set* operations and list mutations are recorded.
func (x GetServiceInfoResponse) SetRecording(enabled bool) GetServiceInfoResponse {
    x.s.SetRecording(enabled)
    return x
}

// Recording returns whether mutation recording is enabled.
func (x GetServiceInfoResponse) Recording() bool {
    return x.s.Recording()
}

// DrainRecordedOps returns all recorded operations since recording was enabled
// (or since the last DrainRecordedOps call) and clears the internal list.
// Use patch.NewPatchFromOps() to convert these to a Patch for application.
func (x GetServiceInfoResponse) DrainRecordedOps() []segment.RecordedOp {
    return x.s.DrainRecordedOps()
}

// RecordedOpsLen returns the number of recorded operations.
func (x GetServiceInfoResponse) RecordedOpsLen() int {
    return x.s.RecordedOpsLen()
}

// GetServiceInfoResponseRaw is a plain Go struct representation of GetServiceInfoResponse.
// Zero values are not set (sparse encoding).
type GetServiceInfoResponseRaw struct {
    Service *ServiceInfoRaw
    Found bool
}

// NewGetServiceInfoResponseFromRaw creates a new GetServiceInfoResponse from a Raw struct representation.
// Only non-zero values are set (sparse encoding).
func NewGetServiceInfoResponseFromRaw(ctx context.Context, raw GetServiceInfoResponseRaw) GetServiceInfoResponse {
    x := NewGetServiceInfoResponse(ctx)
    if raw.Service != nil {
        x.SetService(NewServiceInfoFromRaw(ctx, *raw.Service))
    }
    if raw.Found {
        x.SetFound(raw.Found)
    }
    return x
}

// ToRaw converts the struct to a plain Go struct representation.
func (x GetServiceInfoResponse) ToRaw(ctx context.Context) GetServiceInfoResponseRaw {
    raw := GetServiceInfoResponseRaw{}
    if x.s.HasField(0) {
        nestedRaw := x.Service().ToRaw(ctx)
        raw.Service = &nestedRaw
    }
    raw.Found = x.Found()
    return raw
}
 

// XXXDescr returns the Struct's descriptor. This should only be used
// by the reflect package and is has no compatibility promises like all XXX fields.
//
// Deprecated: No deprecated, but shouldn't be used directly or show up in documentation.
func (x GetServiceInfoResponse) XXXDescr() reflect.StructDescr {
    return XXXPackageDescr.Structs().Get(3)
}

// ListServicesRequest is the request for listing all services.
type ListServicesRequest struct {
   s *segment.Struct
}

// NewListServicesRequest creates a new pooled instance of ListServicesRequest.
// Call Release() when done to return it to the pool for reuse.
func NewListServicesRequest(ctx context.Context) ListServicesRequest {
    s := segment.New(ctx, XXXMappingListServicesRequest)
    return ListServicesRequest{
        s: s,
    }
}

// Release returns the struct to the pool for reuse.
// After calling Release, the struct should not be used.
func (x ListServicesRequest) Release(ctx context.Context) {
    x.s.Release(ctx)
}

// XXXNewListServicesRequestFrom creates a new ListServicesRequest from our internal Struct representation.
// As with all things marked XXX*, this should not be used and has not compatibility
// guarantees.
//
// Deprecated: This is not actually deprecated, but it should not be used directly nor
// show up in any documentation.
func XXXNewListServicesRequestFrom(s *segment.Struct) ListServicesRequest {
    return ListServicesRequest{s: s}
}

// Marshal marshal's the Struct to []byte. The returned slice is shared by Struct,
// so Struct must not be modified after this call. If Struct needs to be modified,
// use MarshalSafe() instead.
func (x ListServicesRequest) Marshal() ([]byte, error) {
    return x.s.Marshal()
}

// MarshalSafe marshal's the Struct to []byte. The returned slice is a copy
// and safe to modify.
func (x ListServicesRequest) MarshalSafe() ([]byte, error) {
    return x.s.MarshalSafe()
}

// MarshalWriter marshals to an io.Writer.
func (x ListServicesRequest) MarshalWriter(w io.Writer) (n int, err error) {
    return x.s.MarshalWriter(w)
}

// Unmarshal unmarshals b into the Struct.
func (x ListServicesRequest) Unmarshal(b []byte) error {
    return x.s.Unmarshal(b)
}

// UnmarshalReader unmarshals a Struct from an io.Reader.
func (x ListServicesRequest) UnmarshalReader (r io.Reader) (int, error) {
    return x.s.UnmarshalReader(r)
}

// Reserved for future use (claw requires at least one field).

func (x ListServicesRequest) Reserved() uint8 {
    return segment.GetUint8(x.s, 0)
}

func (x ListServicesRequest) SetReserved(value uint8) ListServicesRequest {
    segment.SetUint8(x.s, 0, value)
    return x
}



// ClawStruct returns a reflection type representing the Struct.
func (x ListServicesRequest) ClawStruct() reflect.Struct{
    return reflect.XXXNewStruct(x.s, x.XXXDescr())
}

// XXXGetStruct returns the internal Struct representation. Like all XXX* types/methods,
// this should not be used and has no compatibility guarantees.
//
// Deprecated: Not deprectated, but should not be used and should not show up in documentation.
func (x ListServicesRequest) XXXGetStruct() *segment.Struct {
    return x.s
}

// XXXTypeHash returns the SHAKE128 hash (128 bits) of this type's identity.
// Used for Any type serialization to identify the concrete type.
//
// Deprecated: Not deprecated, but should not be used directly and should not show up in documentation.
func (x ListServicesRequest) XXXTypeHash() [16]byte {
    return XXXTypeHashListServicesRequest
}

// SetRecording enables or disables mutation recording for patch generation.
// When enabled, all Set* operations and list mutations are recorded.
func (x ListServicesRequest) SetRecording(enabled bool) ListServicesRequest {
    x.s.SetRecording(enabled)
    return x
}

// Recording returns whether mutation recording is enabled.
func (x ListServicesRequest) Recording() bool {
    return x.s.Recording()
}

// DrainRecordedOps returns all recorded operations since recording was enabled
// (or since the last DrainRecordedOps call) and clears the internal list.
// Use patch.NewPatchFromOps() to convert these to a Patch for application.
func (x ListServicesRequest) DrainRecordedOps() []segment.RecordedOp {
    return x.s.DrainRecordedOps()
}

// RecordedOpsLen returns the number of recorded operations.
func (x ListServicesRequest) RecordedOpsLen() int {
    return x.s.RecordedOpsLen()
}

// ListServicesRequestRaw is a plain Go struct representation of ListServicesRequest.
// Zero values are not set (sparse encoding).
type ListServicesRequestRaw struct {
    Reserved uint8
}

// NewListServicesRequestFromRaw creates a new ListServicesRequest from a Raw struct representation.
// Only non-zero values are set (sparse encoding).
func NewListServicesRequestFromRaw(ctx context.Context, raw ListServicesRequestRaw) ListServicesRequest {
    x := NewListServicesRequest(ctx)
    if raw.Reserved != 0 {
        x.SetReserved(raw.Reserved)
    }
    return x
}

// ToRaw converts the struct to a plain Go struct representation.
func (x ListServicesRequest) ToRaw(ctx context.Context) ListServicesRequestRaw {
    raw := ListServicesRequestRaw{}
    raw.Reserved = x.Reserved()
    return raw
}
 

// XXXDescr returns the Struct's descriptor. This should only be used
// by the reflect package and is has no compatibility promises like all XXX fields.
//
// Deprecated: No deprecated, but shouldn't be used directly or show up in documentation.
func (x ListServicesRequest) XXXDescr() reflect.StructDescr {
    return XXXPackageDescr.Structs().Get(4)
}

// ListServicesResponse is the response containing all registered services.
type ListServicesResponse struct {
   s *segment.Struct
}

// NewListServicesResponse creates a new pooled instance of ListServicesResponse.
// Call Release() when done to return it to the pool for reuse.
func NewListServicesResponse(ctx context.Context) ListServicesResponse {
    s := segment.New(ctx, XXXMappingListServicesResponse)
    return ListServicesResponse{
        s: s,
    }
}

// Release returns the struct to the pool for reuse.
// After calling Release, the struct should not be used.
func (x ListServicesResponse) Release(ctx context.Context) {
    x.s.Release(ctx)
}

// XXXNewListServicesResponseFrom creates a new ListServicesResponse from our internal Struct representation.
// As with all things marked XXX*, this should not be used and has not compatibility
// guarantees.
//
// Deprecated: This is not actually deprecated, but it should not be used directly nor
// show up in any documentation.
func XXXNewListServicesResponseFrom(s *segment.Struct) ListServicesResponse {
    return ListServicesResponse{s: s}
}

// Marshal marshal's the Struct to []byte. The returned slice is shared by Struct,
// so Struct must not be modified after this call. If Struct needs to be modified,
// use MarshalSafe() instead.
func (x ListServicesResponse) Marshal() ([]byte, error) {
    return x.s.Marshal()
}

// MarshalSafe marshal's the Struct to []byte. The returned slice is a copy
// and safe to modify.
func (x ListServicesResponse) MarshalSafe() ([]byte, error) {
    return x.s.MarshalSafe()
}

// MarshalWriter marshals to an io.Writer.
func (x ListServicesResponse) MarshalWriter(w io.Writer) (n int, err error) {
    return x.s.MarshalWriter(w)
}

// Unmarshal unmarshals b into the Struct.
func (x ListServicesResponse) Unmarshal(b []byte) error {
    return x.s.Unmarshal(b)
}

// UnmarshalReader unmarshals a Struct from an io.Reader.
func (x ListServicesResponse) UnmarshalReader (r io.Reader) (int, error) {
    return x.s.UnmarshalReader(r)
}

// Packages is the list of all registered packages with their services.
// PackagesList returns the underlying Structs list for iteration.
// Use NewPackageInfo() to create items and Append to add them.
func (x ListServicesResponse) PackagesList(ctx context.Context) *segment.Structs {
    // Try to get cached or parse from segment
    if structs := segment.GetListStructs(ctx, x.s, 0, XXXMappingPackageInfo); structs != nil {
        return structs
    }
    // Create new empty list if no data exists
    structs := segment.NewStructs(ctx, x.s, 0, XXXMappingPackageInfo)
    return structs
}

// PackagesLen returns the number of items in the list.
func (x ListServicesResponse) PackagesLen(ctx context.Context) int {
    return x.PackagesList(ctx).Len()
}

// PackagesGet returns the item at the given index.
func (x ListServicesResponse) PackagesGet(ctx context.Context, index int) PackageInfo {
    s := x.PackagesList(ctx).Get(index)
    return PackageInfo{s: s}
}

// PackagesAppend appends items to the list.
func (x ListServicesResponse) PackagesAppend(ctx context.Context, values ...PackageInfo) {
    list := x.PackagesList(ctx)
    for _, v := range values {
        list.Append(v.XXXGetStruct())
    }
}

// PackagesAppendRaw appends items to the list using Raw struct representations.
func (x ListServicesResponse) PackagesAppendRaw(ctx context.Context, values ...*PackageInfoRaw) {
    list := x.PackagesList(ctx)
    for _, raw := range values {
        if raw != nil {
            list.Append(NewPackageInfoFromRaw(ctx, *raw).XXXGetStruct())
        }
    }
}



// ClawStruct returns a reflection type representing the Struct.
func (x ListServicesResponse) ClawStruct() reflect.Struct{
    return reflect.XXXNewStruct(x.s, x.XXXDescr())
}

// XXXGetStruct returns the internal Struct representation. Like all XXX* types/methods,
// this should not be used and has no compatibility guarantees.
//
// Deprecated: Not deprectated, but should not be used and should not show up in documentation.
func (x ListServicesResponse) XXXGetStruct() *segment.Struct {
    return x.s
}

// XXXTypeHash returns the SHAKE128 hash (128 bits) of this type's identity.
// Used for Any type serialization to identify the concrete type.
//
// Deprecated: Not deprecated, but should not be used directly and should not show up in documentation.
func (x ListServicesResponse) XXXTypeHash() [16]byte {
    return XXXTypeHashListServicesResponse
}

// SetRecording enables or disables mutation recording for patch generation.
// When enabled, all Set* operations and list mutations are recorded.
func (x ListServicesResponse) SetRecording(enabled bool) ListServicesResponse {
    x.s.SetRecording(enabled)
    return x
}

// Recording returns whether mutation recording is enabled.
func (x ListServicesResponse) Recording() bool {
    return x.s.Recording()
}

// DrainRecordedOps returns all recorded operations since recording was enabled
// (or since the last DrainRecordedOps call) and clears the internal list.
// Use patch.NewPatchFromOps() to convert these to a Patch for application.
func (x ListServicesResponse) DrainRecordedOps() []segment.RecordedOp {
    return x.s.DrainRecordedOps()
}

// RecordedOpsLen returns the number of recorded operations.
func (x ListServicesResponse) RecordedOpsLen() int {
    return x.s.RecordedOpsLen()
}

// ListServicesResponseRaw is a plain Go struct representation of ListServicesResponse.
// Zero values are not set (sparse encoding).
type ListServicesResponseRaw struct {
    Packages []*PackageInfoRaw
}

// NewListServicesResponseFromRaw creates a new ListServicesResponse from a Raw struct representation.
// Only non-zero values are set (sparse encoding).
func NewListServicesResponseFromRaw(ctx context.Context, raw ListServicesResponseRaw) ListServicesResponse {
    x := NewListServicesResponse(ctx)
    if raw.Packages != nil {
        list := x.PackagesList(ctx)
        items := make([]*segment.Struct, 0, len(raw.Packages))
        for _, r := range raw.Packages {
            if r != nil {
                items = append(items, NewPackageInfoFromRaw(ctx, *r).XXXGetStruct())
            }
        }
        list.SetAll(items)
    }
    return x
}

// ToRaw converts the struct to a plain Go struct representation.
func (x ListServicesResponse) ToRaw(ctx context.Context) ListServicesResponseRaw {
    raw := ListServicesResponseRaw{}
    if l := x.s.GetList(0); l != nil && l.(*segment.Structs).Len() > 0 {
        list := l.(*segment.Structs)
        raw.Packages = make([]*PackageInfoRaw, list.Len())
        for i := 0; i < list.Len(); i++ {
            item := PackageInfo{s: list.Get(i)}
            itemRaw := item.ToRaw(ctx)
            raw.Packages[i] = &itemRaw
        }
    } else if x.s.HasField(0) {
        list := x.PackagesList(ctx)
        raw.Packages = make([]*PackageInfoRaw, list.Len())
        for i := 0; i < list.Len(); i++ {
            item := PackageInfo{s: list.Get(i)}
            itemRaw := item.ToRaw(ctx)
            raw.Packages[i] = &itemRaw
        }
    }
    return raw
}
 

// XXXDescr returns the Struct's descriptor. This should only be used
// by the reflect package and is has no compatibility promises like all XXX fields.
//
// Deprecated: No deprecated, but shouldn't be used directly or show up in documentation.
func (x ListServicesResponse) XXXDescr() reflect.StructDescr {
    return XXXPackageDescr.Structs().Get(5)
}

// MethodInfo contains information about a single RPC method.
type MethodInfo struct {
   s *segment.Struct
}

// NewMethodInfo creates a new pooled instance of MethodInfo.
// Call Release() when done to return it to the pool for reuse.
func NewMethodInfo(ctx context.Context) MethodInfo {
    s := segment.New(ctx, XXXMappingMethodInfo)
    return MethodInfo{
        s: s,
    }
}

// Release returns the struct to the pool for reuse.
// After calling Release, the struct should not be used.
func (x MethodInfo) Release(ctx context.Context) {
    x.s.Release(ctx)
}

// XXXNewMethodInfoFrom creates a new MethodInfo from our internal Struct representation.
// As with all things marked XXX*, this should not be used and has not compatibility
// guarantees.
//
// Deprecated: This is not actually deprecated, but it should not be used directly nor
// show up in any documentation.
func XXXNewMethodInfoFrom(s *segment.Struct) MethodInfo {
    return MethodInfo{s: s}
}

// Marshal marshal's the Struct to []byte. The returned slice is shared by Struct,
// so Struct must not be modified after this call. If Struct needs to be modified,
// use MarshalSafe() instead.
func (x MethodInfo) Marshal() ([]byte, error) {
    return x.s.Marshal()
}

// MarshalSafe marshal's the Struct to []byte. The returned slice is a copy
// and safe to modify.
func (x MethodInfo) MarshalSafe() ([]byte, error) {
    return x.s.MarshalSafe()
}

// MarshalWriter marshals to an io.Writer.
func (x MethodInfo) MarshalWriter(w io.Writer) (n int, err error) {
    return x.s.MarshalWriter(w)
}

// Unmarshal unmarshals b into the Struct.
func (x MethodInfo) Unmarshal(b []byte) error {
    return x.s.Unmarshal(b)
}

// UnmarshalReader unmarshals a Struct from an io.Reader.
func (x MethodInfo) UnmarshalReader (r io.Reader) (int, error) {
    return x.s.UnmarshalReader(r)
}

// Name is the method name.
func (x MethodInfo) Name() string {
    return segment.GetString(x.s, 0)
}

func (x MethodInfo) SetName(value string) MethodInfo {
    segment.SetString(x.s, 0, value)
    return x
}

// Type is the RPC type (synchronous, send, recv, bidirectional).
func (x MethodInfo) Type() msgs.RPCType {
    return msgs.RPCType(segment.GetUint8(x.s, 1))
}

func (x MethodInfo) SetType(value msgs.RPCType) MethodInfo {
    segment.SetUint8(x.s, 1, uint8(value))
    return x
}



// ClawStruct returns a reflection type representing the Struct.
func (x MethodInfo) ClawStruct() reflect.Struct{
    return reflect.XXXNewStruct(x.s, x.XXXDescr())
}

// XXXGetStruct returns the internal Struct representation. Like all XXX* types/methods,
// this should not be used and has no compatibility guarantees.
//
// Deprecated: Not deprectated, but should not be used and should not show up in documentation.
func (x MethodInfo) XXXGetStruct() *segment.Struct {
    return x.s
}

// XXXTypeHash returns the SHAKE128 hash (128 bits) of this type's identity.
// Used for Any type serialization to identify the concrete type.
//
// Deprecated: Not deprecated, but should not be used directly and should not show up in documentation.
func (x MethodInfo) XXXTypeHash() [16]byte {
    return XXXTypeHashMethodInfo
}

// SetRecording enables or disables mutation recording for patch generation.
// When enabled, all Set* operations and list mutations are recorded.
func (x MethodInfo) SetRecording(enabled bool) MethodInfo {
    x.s.SetRecording(enabled)
    return x
}

// Recording returns whether mutation recording is enabled.
func (x MethodInfo) Recording() bool {
    return x.s.Recording()
}

// DrainRecordedOps returns all recorded operations since recording was enabled
// (or since the last DrainRecordedOps call) and clears the internal list.
// Use patch.NewPatchFromOps() to convert these to a Patch for application.
func (x MethodInfo) DrainRecordedOps() []segment.RecordedOp {
    return x.s.DrainRecordedOps()
}

// RecordedOpsLen returns the number of recorded operations.
func (x MethodInfo) RecordedOpsLen() int {
    return x.s.RecordedOpsLen()
}

// MethodInfoRaw is a plain Go struct representation of MethodInfo.
// Zero values are not set (sparse encoding).
type MethodInfoRaw struct {
    Name string
    Type msgs.RPCType
}

// NewMethodInfoFromRaw creates a new MethodInfo from a Raw struct representation.
// Only non-zero values are set (sparse encoding).
func NewMethodInfoFromRaw(ctx context.Context, raw MethodInfoRaw) MethodInfo {
    x := NewMethodInfo(ctx)
    if raw.Name != "" {
        x.SetName(raw.Name)
    }
    if raw.Type != 0 {
        x.SetType(raw.Type)
    }
    return x
}

// ToRaw converts the struct to a plain Go struct representation.
func (x MethodInfo) ToRaw(ctx context.Context) MethodInfoRaw {
    raw := MethodInfoRaw{}
    raw.Name = x.Name()
    raw.Type = x.Type()
    return raw
}
 

// XXXDescr returns the Struct's descriptor. This should only be used
// by the reflect package and is has no compatibility promises like all XXX fields.
//
// Deprecated: No deprecated, but shouldn't be used directly or show up in documentation.
func (x MethodInfo) XXXDescr() reflect.StructDescr {
    return XXXPackageDescr.Structs().Get(6)
}

// PackageInfo contains information about a package and its services.
type PackageInfo struct {
   s *segment.Struct
}

// NewPackageInfo creates a new pooled instance of PackageInfo.
// Call Release() when done to return it to the pool for reuse.
func NewPackageInfo(ctx context.Context) PackageInfo {
    s := segment.New(ctx, XXXMappingPackageInfo)
    return PackageInfo{
        s: s,
    }
}

// Release returns the struct to the pool for reuse.
// After calling Release, the struct should not be used.
func (x PackageInfo) Release(ctx context.Context) {
    x.s.Release(ctx)
}

// XXXNewPackageInfoFrom creates a new PackageInfo from our internal Struct representation.
// As with all things marked XXX*, this should not be used and has not compatibility
// guarantees.
//
// Deprecated: This is not actually deprecated, but it should not be used directly nor
// show up in any documentation.
func XXXNewPackageInfoFrom(s *segment.Struct) PackageInfo {
    return PackageInfo{s: s}
}

// Marshal marshal's the Struct to []byte. The returned slice is shared by Struct,
// so Struct must not be modified after this call. If Struct needs to be modified,
// use MarshalSafe() instead.
func (x PackageInfo) Marshal() ([]byte, error) {
    return x.s.Marshal()
}

// MarshalSafe marshal's the Struct to []byte. The returned slice is a copy
// and safe to modify.
func (x PackageInfo) MarshalSafe() ([]byte, error) {
    return x.s.MarshalSafe()
}

// MarshalWriter marshals to an io.Writer.
func (x PackageInfo) MarshalWriter(w io.Writer) (n int, err error) {
    return x.s.MarshalWriter(w)
}

// Unmarshal unmarshals b into the Struct.
func (x PackageInfo) Unmarshal(b []byte) error {
    return x.s.Unmarshal(b)
}

// UnmarshalReader unmarshals a Struct from an io.Reader.
func (x PackageInfo) UnmarshalReader (r io.Reader) (int, error) {
    return x.s.UnmarshalReader(r)
}

// Name is the package name.
func (x PackageInfo) Name() string {
    return segment.GetString(x.s, 0)
}

func (x PackageInfo) SetName(value string) PackageInfo {
    segment.SetString(x.s, 0, value)
    return x
}

// Services is the list of services in this package.
// ServicesList returns the underlying Structs list for iteration.
// Use NewServiceInfo() to create items and Append to add them.
func (x PackageInfo) ServicesList(ctx context.Context) *segment.Structs {
    // Try to get cached or parse from segment
    if structs := segment.GetListStructs(ctx, x.s, 1, XXXMappingServiceInfo); structs != nil {
        return structs
    }
    // Create new empty list if no data exists
    structs := segment.NewStructs(ctx, x.s, 1, XXXMappingServiceInfo)
    return structs
}

// ServicesLen returns the number of items in the list.
func (x PackageInfo) ServicesLen(ctx context.Context) int {
    return x.ServicesList(ctx).Len()
}

// ServicesGet returns the item at the given index.
func (x PackageInfo) ServicesGet(ctx context.Context, index int) ServiceInfo {
    s := x.ServicesList(ctx).Get(index)
    return ServiceInfo{s: s}
}

// ServicesAppend appends items to the list.
func (x PackageInfo) ServicesAppend(ctx context.Context, values ...ServiceInfo) {
    list := x.ServicesList(ctx)
    for _, v := range values {
        list.Append(v.XXXGetStruct())
    }
}

// ServicesAppendRaw appends items to the list using Raw struct representations.
func (x PackageInfo) ServicesAppendRaw(ctx context.Context, values ...*ServiceInfoRaw) {
    list := x.ServicesList(ctx)
    for _, raw := range values {
        if raw != nil {
            list.Append(NewServiceInfoFromRaw(ctx, *raw).XXXGetStruct())
        }
    }
}



// ClawStruct returns a reflection type representing the Struct.
func (x PackageInfo) ClawStruct() reflect.Struct{
    return reflect.XXXNewStruct(x.s, x.XXXDescr())
}

// XXXGetStruct returns the internal Struct representation. Like all XXX* types/methods,
// this should not be used and has no compatibility guarantees.
//
// Deprecated: Not deprectated, but should not be used and should not show up in documentation.
func (x PackageInfo) XXXGetStruct() *segment.Struct {
    return x.s
}

// XXXTypeHash returns the SHAKE128 hash (128 bits) of this type's identity.
// Used for Any type serialization to identify the concrete type.
//
// Deprecated: Not deprecated, but should not be used directly and should not show up in documentation.
func (x PackageInfo) XXXTypeHash() [16]byte {
    return XXXTypeHashPackageInfo
}

// SetRecording enables or disables mutation recording for patch generation.
// When enabled, all Set* operations and list mutations are recorded.
func (x PackageInfo) SetRecording(enabled bool) PackageInfo {
    x.s.SetRecording(enabled)
    return x
}

// Recording returns whether mutation recording is enabled.
func (x PackageInfo) Recording() bool {
    return x.s.Recording()
}

// DrainRecordedOps returns all recorded operations since recording was enabled
// (or since the last DrainRecordedOps call) and clears the internal list.
// Use patch.NewPatchFromOps() to convert these to a Patch for application.
func (x PackageInfo) DrainRecordedOps() []segment.RecordedOp {
    return x.s.DrainRecordedOps()
}

// RecordedOpsLen returns the number of recorded operations.
func (x PackageInfo) RecordedOpsLen() int {
    return x.s.RecordedOpsLen()
}

// PackageInfoRaw is a plain Go struct representation of PackageInfo.
// Zero values are not set (sparse encoding).
type PackageInfoRaw struct {
    Name string
    Services []*ServiceInfoRaw
}

// NewPackageInfoFromRaw creates a new PackageInfo from a Raw struct representation.
// Only non-zero values are set (sparse encoding).
func NewPackageInfoFromRaw(ctx context.Context, raw PackageInfoRaw) PackageInfo {
    x := NewPackageInfo(ctx)
    if raw.Name != "" {
        x.SetName(raw.Name)
    }
    if raw.Services != nil {
        list := x.ServicesList(ctx)
        items := make([]*segment.Struct, 0, len(raw.Services))
        for _, r := range raw.Services {
            if r != nil {
                items = append(items, NewServiceInfoFromRaw(ctx, *r).XXXGetStruct())
            }
        }
        list.SetAll(items)
    }
    return x
}

// ToRaw converts the struct to a plain Go struct representation.
func (x PackageInfo) ToRaw(ctx context.Context) PackageInfoRaw {
    raw := PackageInfoRaw{}
    raw.Name = x.Name()
    if l := x.s.GetList(1); l != nil && l.(*segment.Structs).Len() > 0 {
        list := l.(*segment.Structs)
        raw.Services = make([]*ServiceInfoRaw, list.Len())
        for i := 0; i < list.Len(); i++ {
            item := ServiceInfo{s: list.Get(i)}
            itemRaw := item.ToRaw(ctx)
            raw.Services[i] = &itemRaw
        }
    } else if x.s.HasField(1) {
        list := x.ServicesList(ctx)
        raw.Services = make([]*ServiceInfoRaw, list.Len())
        for i := 0; i < list.Len(); i++ {
            item := ServiceInfo{s: list.Get(i)}
            itemRaw := item.ToRaw(ctx)
            raw.Services[i] = &itemRaw
        }
    }
    return raw
}
 

// XXXDescr returns the Struct's descriptor. This should only be used
// by the reflect package and is has no compatibility promises like all XXX fields.
//
// Deprecated: No deprecated, but shouldn't be used directly or show up in documentation.
func (x PackageInfo) XXXDescr() reflect.StructDescr {
    return XXXPackageDescr.Structs().Get(7)
}

// ServiceInfo contains information about a service and its methods.
type ServiceInfo struct {
   s *segment.Struct
}

// NewServiceInfo creates a new pooled instance of ServiceInfo.
// Call Release() when done to return it to the pool for reuse.
func NewServiceInfo(ctx context.Context) ServiceInfo {
    s := segment.New(ctx, XXXMappingServiceInfo)
    return ServiceInfo{
        s: s,
    }
}

// Release returns the struct to the pool for reuse.
// After calling Release, the struct should not be used.
func (x ServiceInfo) Release(ctx context.Context) {
    x.s.Release(ctx)
}

// XXXNewServiceInfoFrom creates a new ServiceInfo from our internal Struct representation.
// As with all things marked XXX*, this should not be used and has not compatibility
// guarantees.
//
// Deprecated: This is not actually deprecated, but it should not be used directly nor
// show up in any documentation.
func XXXNewServiceInfoFrom(s *segment.Struct) ServiceInfo {
    return ServiceInfo{s: s}
}

// Marshal marshal's the Struct to []byte. The returned slice is shared by Struct,
// so Struct must not be modified after this call. If Struct needs to be modified,
// use MarshalSafe() instead.
func (x ServiceInfo) Marshal() ([]byte, error) {
    return x.s.Marshal()
}

// MarshalSafe marshal's the Struct to []byte. The returned slice is a copy
// and safe to modify.
func (x ServiceInfo) MarshalSafe() ([]byte, error) {
    return x.s.MarshalSafe()
}

// MarshalWriter marshals to an io.Writer.
func (x ServiceInfo) MarshalWriter(w io.Writer) (n int, err error) {
    return x.s.MarshalWriter(w)
}

// Unmarshal unmarshals b into the Struct.
func (x ServiceInfo) Unmarshal(b []byte) error {
    return x.s.Unmarshal(b)
}

// UnmarshalReader unmarshals a Struct from an io.Reader.
func (x ServiceInfo) UnmarshalReader (r io.Reader) (int, error) {
    return x.s.UnmarshalReader(r)
}

// Name is the service name.
func (x ServiceInfo) Name() string {
    return segment.GetString(x.s, 0)
}

func (x ServiceInfo) SetName(value string) ServiceInfo {
    segment.SetString(x.s, 0, value)
    return x
}

// Methods is the list of methods in this service.
// MethodsList returns the underlying Structs list for iteration.
// Use NewMethodInfo() to create items and Append to add them.
func (x ServiceInfo) MethodsList(ctx context.Context) *segment.Structs {
    // Try to get cached or parse from segment
    if structs := segment.GetListStructs(ctx, x.s, 1, XXXMappingMethodInfo); structs != nil {
        return structs
    }
    // Create new empty list if no data exists
    structs := segment.NewStructs(ctx, x.s, 1, XXXMappingMethodInfo)
    return structs
}

// MethodsLen returns the number of items in the list.
func (x ServiceInfo) MethodsLen(ctx context.Context) int {
    return x.MethodsList(ctx).Len()
}

// MethodsGet returns the item at the given index.
func (x ServiceInfo) MethodsGet(ctx context.Context, index int) MethodInfo {
    s := x.MethodsList(ctx).Get(index)
    return MethodInfo{s: s}
}

// MethodsAppend appends items to the list.
func (x ServiceInfo) MethodsAppend(ctx context.Context, values ...MethodInfo) {
    list := x.MethodsList(ctx)
    for _, v := range values {
        list.Append(v.XXXGetStruct())
    }
}

// MethodsAppendRaw appends items to the list using Raw struct representations.
func (x ServiceInfo) MethodsAppendRaw(ctx context.Context, values ...*MethodInfoRaw) {
    list := x.MethodsList(ctx)
    for _, raw := range values {
        if raw != nil {
            list.Append(NewMethodInfoFromRaw(ctx, *raw).XXXGetStruct())
        }
    }
}



// ClawStruct returns a reflection type representing the Struct.
func (x ServiceInfo) ClawStruct() reflect.Struct{
    return reflect.XXXNewStruct(x.s, x.XXXDescr())
}

// XXXGetStruct returns the internal Struct representation. Like all XXX* types/methods,
// this should not be used and has no compatibility guarantees.
//
// Deprecated: Not deprectated, but should not be used and should not show up in documentation.
func (x ServiceInfo) XXXGetStruct() *segment.Struct {
    return x.s
}

// XXXTypeHash returns the SHAKE128 hash (128 bits) of this type's identity.
// Used for Any type serialization to identify the concrete type.
//
// Deprecated: Not deprecated, but should not be used directly and should not show up in documentation.
func (x ServiceInfo) XXXTypeHash() [16]byte {
    return XXXTypeHashServiceInfo
}

// SetRecording enables or disables mutation recording for patch generation.
// When enabled, all Set* operations and list mutations are recorded.
func (x ServiceInfo) SetRecording(enabled bool) ServiceInfo {
    x.s.SetRecording(enabled)
    return x
}

// Recording returns whether mutation recording is enabled.
func (x ServiceInfo) Recording() bool {
    return x.s.Recording()
}

// DrainRecordedOps returns all recorded operations since recording was enabled
// (or since the last DrainRecordedOps call) and clears the internal list.
// Use patch.NewPatchFromOps() to convert these to a Patch for application.
func (x ServiceInfo) DrainRecordedOps() []segment.RecordedOp {
    return x.s.DrainRecordedOps()
}

// RecordedOpsLen returns the number of recorded operations.
func (x ServiceInfo) RecordedOpsLen() int {
    return x.s.RecordedOpsLen()
}

// ServiceInfoRaw is a plain Go struct representation of ServiceInfo.
// Zero values are not set (sparse encoding).
type ServiceInfoRaw struct {
    Name string
    Methods []*MethodInfoRaw
}

// NewServiceInfoFromRaw creates a new ServiceInfo from a Raw struct representation.
// Only non-zero values are set (sparse encoding).
func NewServiceInfoFromRaw(ctx context.Context, raw ServiceInfoRaw) ServiceInfo {
    x := NewServiceInfo(ctx)
    if raw.Name != "" {
        x.SetName(raw.Name)
    }
    if raw.Methods != nil {
        list := x.MethodsList(ctx)
        items := make([]*segment.Struct, 0, len(raw.Methods))
        for _, r := range raw.Methods {
            if r != nil {
                items = append(items, NewMethodInfoFromRaw(ctx, *r).XXXGetStruct())
            }
        }
        list.SetAll(items)
    }
    return x
}

// ToRaw converts the struct to a plain Go struct representation.
func (x ServiceInfo) ToRaw(ctx context.Context) ServiceInfoRaw {
    raw := ServiceInfoRaw{}
    raw.Name = x.Name()
    if l := x.s.GetList(1); l != nil && l.(*segment.Structs).Len() > 0 {
        list := l.(*segment.Structs)
        raw.Methods = make([]*MethodInfoRaw, list.Len())
        for i := 0; i < list.Len(); i++ {
            item := MethodInfo{s: list.Get(i)}
            itemRaw := item.ToRaw(ctx)
            raw.Methods[i] = &itemRaw
        }
    } else if x.s.HasField(1) {
        list := x.MethodsList(ctx)
        raw.Methods = make([]*MethodInfoRaw, list.Len())
        for i := 0; i < list.Len(); i++ {
            item := MethodInfo{s: list.Get(i)}
            itemRaw := item.ToRaw(ctx)
            raw.Methods[i] = &itemRaw
        }
    }
    return raw
}
 

// XXXDescr returns the Struct's descriptor. This should only be used
// by the reflect package and is has no compatibility promises like all XXX fields.
//
// Deprecated: No deprecated, but shouldn't be used directly or show up in documentation.
func (x ServiceInfo) XXXDescr() reflect.StructDescr {
    return XXXPackageDescr.Structs().Get(8)
} 

// Everything below this line is internal details.

// Type hash constants for Any type support.
// These are SHAKE128 hashes (128 bits) of the full type path + name.
// Deprecated: Not deprecated, but shouldn't be used directly or show up in documentation.
var XXXTypeHashGetMethodInfoRequest = [16]byte{0x0a, 0x95, 0xca, 0x1f, 0x78, 0xc2, 0xf3, 0x75, 0x02, 0xfe, 0x9c, 0xd4, 0xa0, 0xd7, 0x29, 0xcf}

// Deprecated: Not deprecated, but shouldn't be used directly or show up in documentation.
var XXXTypeHashGetMethodInfoResponse = [16]byte{0x18, 0xc9, 0xbe, 0xc8, 0x91, 0xc4, 0x15, 0xc2, 0x2b, 0xec, 0x09, 0x0b, 0x9b, 0x56, 0x9f, 0xe5}

// Deprecated: Not deprecated, but shouldn't be used directly or show up in documentation.
var XXXTypeHashGetServiceInfoRequest = [16]byte{0x36, 0xee, 0x2a, 0x23, 0x1c, 0x36, 0x68, 0x17, 0xb9, 0x21, 0xe0, 0x0d, 0xde, 0x13, 0x34, 0x67}

// Deprecated: Not deprecated, but shouldn't be used directly or show up in documentation.
var XXXTypeHashGetServiceInfoResponse = [16]byte{0xfe, 0x16, 0xdd, 0xb8, 0xc6, 0x04, 0xb9, 0x07, 0xe7, 0x6f, 0x66, 0x1e, 0x54, 0xfd, 0x72, 0x85}

// Deprecated: Not deprecated, but shouldn't be used directly or show up in documentation.
var XXXTypeHashListServicesRequest = [16]byte{0x59, 0x1b, 0xec, 0x3d, 0x59, 0xa7, 0x18, 0x33, 0xf2, 0xbb, 0x14, 0xf6, 0xe7, 0x41, 0x43, 0xc7}

// Deprecated: Not deprecated, but shouldn't be used directly or show up in documentation.
var XXXTypeHashListServicesResponse = [16]byte{0x74, 0xf1, 0x4f, 0x07, 0x09, 0x88, 0xaf, 0x2e, 0x15, 0x63, 0x76, 0x86, 0x4f, 0x27, 0x7d, 0xb1}

// Deprecated: Not deprecated, but shouldn't be used directly or show up in documentation.
var XXXTypeHashMethodInfo = [16]byte{0x3e, 0x80, 0xd3, 0xae, 0xf0, 0x6c, 0xf0, 0xd8, 0x81, 0x77, 0xc8, 0x4e, 0x41, 0x64, 0x6f, 0x81}

// Deprecated: Not deprecated, but shouldn't be used directly or show up in documentation.
var XXXTypeHashPackageInfo = [16]byte{0x9e, 0x1d, 0x2a, 0x24, 0xd2, 0x04, 0x37, 0xa1, 0x86, 0x3d, 0x28, 0xd4, 0xbd, 0x22, 0x67, 0xe6}

// Deprecated: Not deprecated, but shouldn't be used directly or show up in documentation.
var XXXTypeHashServiceInfo = [16]byte{0xc4, 0xdc, 0xa6, 0xc1, 0x6e, 0xa9, 0xa2, 0x02, 0x95, 0xcf, 0xf3, 0x6f, 0xc5, 0xc5, 0x08, 0x15}

// Deprecated: Not deprecated, but shouldn't be used directly or show up in documentation.
var XXXMappingGetMethodInfoRequest = &mapping.Map{
    Name: "GetMethodInfoRequest",
    Pkg: "reflection",
    Path: "github.com/bearlytools/claw/rpc/reflection",
    Fields: []*mapping.FieldDescr{
        {
            Name: "Package",
            Type: field.FTString,
            Package: "reflection",
            FullPath: "github.com/bearlytools/claw/rpc/reflection",
            FieldNum: 0,
            IsEnum: false,
            IsAny: false,
        },
        {
            Name: "Service",
            Type: field.FTString,
            Package: "reflection",
            FullPath: "github.com/bearlytools/claw/rpc/reflection",
            FieldNum: 1,
            IsEnum: false,
            IsAny: false,
        },
        {
            Name: "Method",
            Type: field.FTString,
            Package: "reflection",
            FullPath: "github.com/bearlytools/claw/rpc/reflection",
            FieldNum: 2,
            IsEnum: false,
            IsAny: false,
        },
    },
}

// Deprecated: Not deprecated, but shouldn't be used directly or show up in documentation.
var XXXMappingGetMethodInfoResponse = &mapping.Map{
    Name: "GetMethodInfoResponse",
    Pkg: "reflection",
    Path: "github.com/bearlytools/claw/rpc/reflection",
    Fields: []*mapping.FieldDescr{
        {
            Name: "Method",
            Type: field.FTStruct,
            Package: "reflection",
            FullPath: "github.com/bearlytools/claw/rpc/reflection",
            FieldNum: 0,
            IsEnum: false,
            IsAny: false,
            StructName: "MethodInfo",
            
            Mapping: XXXMappingMethodInfo,
        },
        {
            Name: "Found",
            Type: field.FTBool,
            Package: "reflection",
            FullPath: "github.com/bearlytools/claw/rpc/reflection",
            FieldNum: 1,
            IsEnum: false,
            IsAny: false,
        },
    },
}

// Deprecated: Not deprecated, but shouldn't be used directly or show up in documentation.
var XXXMappingGetServiceInfoRequest = &mapping.Map{
    Name: "GetServiceInfoRequest",
    Pkg: "reflection",
    Path: "github.com/bearlytools/claw/rpc/reflection",
    Fields: []*mapping.FieldDescr{
        {
            Name: "Package",
            Type: field.FTString,
            Package: "reflection",
            FullPath: "github.com/bearlytools/claw/rpc/reflection",
            FieldNum: 0,
            IsEnum: false,
            IsAny: false,
        },
        {
            Name: "Service",
            Type: field.FTString,
            Package: "reflection",
            FullPath: "github.com/bearlytools/claw/rpc/reflection",
            FieldNum: 1,
            IsEnum: false,
            IsAny: false,
        },
    },
}

// Deprecated: Not deprecated, but shouldn't be used directly or show up in documentation.
var XXXMappingGetServiceInfoResponse = &mapping.Map{
    Name: "GetServiceInfoResponse",
    Pkg: "reflection",
    Path: "github.com/bearlytools/claw/rpc/reflection",
    Fields: []*mapping.FieldDescr{
        {
            Name: "Service",
            Type: field.FTStruct,
            Package: "reflection",
            FullPath: "github.com/bearlytools/claw/rpc/reflection",
            FieldNum: 0,
            IsEnum: false,
            IsAny: false,
            StructName: "ServiceInfo",
            
            Mapping: XXXMappingServiceInfo,
        },
        {
            Name: "Found",
            Type: field.FTBool,
            Package: "reflection",
            FullPath: "github.com/bearlytools/claw/rpc/reflection",
            FieldNum: 1,
            IsEnum: false,
            IsAny: false,
        },
    },
}

// Deprecated: Not deprecated, but shouldn't be used directly or show up in documentation.
var XXXMappingListServicesRequest = &mapping.Map{
    Name: "ListServicesRequest",
    Pkg: "reflection",
    Path: "github.com/bearlytools/claw/rpc/reflection",
    Fields: []*mapping.FieldDescr{
        {
            Name: "Reserved",
            Type: field.FTUint8,
            Package: "reflection",
            FullPath: "github.com/bearlytools/claw/rpc/reflection",
            FieldNum: 0,
            IsEnum: false,
            IsAny: false,
        },
    },
}

// Deprecated: Not deprecated, but shouldn't be used directly or show up in documentation.
var XXXMappingListServicesResponse = &mapping.Map{
    Name: "ListServicesResponse",
    Pkg: "reflection",
    Path: "github.com/bearlytools/claw/rpc/reflection",
    Fields: []*mapping.FieldDescr{
        {
            Name: "Packages",
            Type: field.FTListStructs,
            Package: "reflection",
            FullPath: "github.com/bearlytools/claw/rpc/reflection",
            FieldNum: 0,
            IsEnum: false,
            IsAny: false,
            StructName: "PackageInfo",
            
            Mapping: XXXMappingPackageInfo,
        },
    },
}

// Deprecated: Not deprecated, but shouldn't be used directly or show up in documentation.
var XXXMappingMethodInfo = &mapping.Map{
    Name: "MethodInfo",
    Pkg: "reflection",
    Path: "github.com/bearlytools/claw/rpc/reflection",
    Fields: []*mapping.FieldDescr{
        {
            Name: "Name",
            Type: field.FTString,
            Package: "reflection",
            FullPath: "github.com/bearlytools/claw/rpc/reflection",
            FieldNum: 0,
            IsEnum: false,
            IsAny: false,
        },
        {
            Name: "Type",
            Type: field.FTUint8,
            Package: "msgs",
            FullPath: "github.com/bearlytools/claw/rpc/internal/msgs",
            FieldNum: 1,
            IsEnum: true,
            IsAny: false,
            EnumGroup: "msgs.RPCType",
        },
    },
}

// Deprecated: Not deprecated, but shouldn't be used directly or show up in documentation.
var XXXMappingPackageInfo = &mapping.Map{
    Name: "PackageInfo",
    Pkg: "reflection",
    Path: "github.com/bearlytools/claw/rpc/reflection",
    Fields: []*mapping.FieldDescr{
        {
            Name: "Name",
            Type: field.FTString,
            Package: "reflection",
            FullPath: "github.com/bearlytools/claw/rpc/reflection",
            FieldNum: 0,
            IsEnum: false,
            IsAny: false,
        },
        {
            Name: "Services",
            Type: field.FTListStructs,
            Package: "reflection",
            FullPath: "github.com/bearlytools/claw/rpc/reflection",
            FieldNum: 1,
            IsEnum: false,
            IsAny: false,
            StructName: "ServiceInfo",
            
            Mapping: XXXMappingServiceInfo,
        },
    },
}

// Deprecated: Not deprecated, but shouldn't be used directly or show up in documentation.
var XXXMappingServiceInfo = &mapping.Map{
    Name: "ServiceInfo",
    Pkg: "reflection",
    Path: "github.com/bearlytools/claw/rpc/reflection",
    Fields: []*mapping.FieldDescr{
        {
            Name: "Name",
            Type: field.FTString,
            Package: "reflection",
            FullPath: "github.com/bearlytools/claw/rpc/reflection",
            FieldNum: 0,
            IsEnum: false,
            IsAny: false,
        },
        {
            Name: "Methods",
            Type: field.FTListStructs,
            Package: "reflection",
            FullPath: "github.com/bearlytools/claw/rpc/reflection",
            FieldNum: 1,
            IsEnum: false,
            IsAny: false,
            StructName: "MethodInfo",
            
            Mapping: XXXMappingMethodInfo,
        },
    },
}


// init initializes all mapping function pointer tables for O(1) dispatch.
func init() {
    XXXMappingGetMethodInfoRequest.Init()
    XXXMappingGetMethodInfoResponse.Init()
    XXXMappingGetServiceInfoRequest.Init()
    XXXMappingGetServiceInfoResponse.Init()
    XXXMappingListServicesRequest.Init()
    XXXMappingListServicesResponse.Init()
    XXXMappingMethodInfo.Init()
    XXXMappingPackageInfo.Init()
    XXXMappingServiceInfo.Init()
}

 


var XXXStructDescrGetMethodInfoRequest = &reflect.XXXStructDescrImpl{
    Name:      "GetMethodInfoRequest",
    Pkg:       XXXMappingGetMethodInfoRequest.Pkg,
    Path:      XXXMappingGetMethodInfoRequest.Path,
    Mapping:   XXXMappingGetMethodInfoRequest,
    FieldList: []reflect.FieldDescr {
        
        reflect.XXXFieldDescrImpl{
            FD:  XXXMappingGetMethodInfoRequest.Fields[0],  
        }, 
        
        reflect.XXXFieldDescrImpl{
            FD:  XXXMappingGetMethodInfoRequest.Fields[1],  
        }, 
        
        reflect.XXXFieldDescrImpl{
            FD:  XXXMappingGetMethodInfoRequest.Fields[2],  
        },  
    },
}

var XXXStructDescrGetMethodInfoResponse = &reflect.XXXStructDescrImpl{
    Name:      "GetMethodInfoResponse",
    Pkg:       XXXMappingGetMethodInfoResponse.Pkg,
    Path:      XXXMappingGetMethodInfoResponse.Path,
    Mapping:   XXXMappingGetMethodInfoResponse,
    FieldList: []reflect.FieldDescr {
        
        reflect.XXXFieldDescrImpl{
            FD:  XXXMappingGetMethodInfoResponse.Fields[0],
            SD: XXXStructDescrMethodInfo,  
        }, 
        
        reflect.XXXFieldDescrImpl{
            FD:  XXXMappingGetMethodInfoResponse.Fields[1],  
        },  
    },
}

var XXXStructDescrGetServiceInfoRequest = &reflect.XXXStructDescrImpl{
    Name:      "GetServiceInfoRequest",
    Pkg:       XXXMappingGetServiceInfoRequest.Pkg,
    Path:      XXXMappingGetServiceInfoRequest.Path,
    Mapping:   XXXMappingGetServiceInfoRequest,
    FieldList: []reflect.FieldDescr {
        
        reflect.XXXFieldDescrImpl{
            FD:  XXXMappingGetServiceInfoRequest.Fields[0],  
        }, 
        
        reflect.XXXFieldDescrImpl{
            FD:  XXXMappingGetServiceInfoRequest.Fields[1],  
        },  
    },
}

var XXXStructDescrGetServiceInfoResponse = &reflect.XXXStructDescrImpl{
    Name:      "GetServiceInfoResponse",
    Pkg:       XXXMappingGetServiceInfoResponse.Pkg,
    Path:      XXXMappingGetServiceInfoResponse.Path,
    Mapping:   XXXMappingGetServiceInfoResponse,
    FieldList: []reflect.FieldDescr {
        
        reflect.XXXFieldDescrImpl{
            FD:  XXXMappingGetServiceInfoResponse.Fields[0],
            SD: XXXStructDescrServiceInfo,  
        }, 
        
        reflect.XXXFieldDescrImpl{
            FD:  XXXMappingGetServiceInfoResponse.Fields[1],  
        },  
    },
}

var XXXStructDescrListServicesRequest = &reflect.XXXStructDescrImpl{
    Name:      "ListServicesRequest",
    Pkg:       XXXMappingListServicesRequest.Pkg,
    Path:      XXXMappingListServicesRequest.Path,
    Mapping:   XXXMappingListServicesRequest,
    FieldList: []reflect.FieldDescr {
        
        reflect.XXXFieldDescrImpl{
            FD:  XXXMappingListServicesRequest.Fields[0],  
        },  
    },
}

var XXXStructDescrListServicesResponse = &reflect.XXXStructDescrImpl{
    Name:      "ListServicesResponse",
    Pkg:       XXXMappingListServicesResponse.Pkg,
    Path:      XXXMappingListServicesResponse.Path,
    Mapping:   XXXMappingListServicesResponse,
    FieldList: []reflect.FieldDescr {
        
        reflect.XXXFieldDescrImpl{
            FD:  XXXMappingListServicesResponse.Fields[0],
            SD: XXXStructDescrPackageInfo,  
        },  
    },
}

var XXXStructDescrMethodInfo = &reflect.XXXStructDescrImpl{
    Name:      "MethodInfo",
    Pkg:       XXXMappingMethodInfo.Pkg,
    Path:      XXXMappingMethodInfo.Path,
    Mapping:   XXXMappingMethodInfo,
    FieldList: []reflect.FieldDescr {
        
        reflect.XXXFieldDescrImpl{
            FD:  XXXMappingMethodInfo.Fields[0],  
        }, 
        
        reflect.XXXFieldDescrImpl{
            FD: XXXMappingMethodInfo.Fields[1],
            EG: msgs.XXXEnumGroupRPCType,
        },
          
    },
}

var XXXStructDescrPackageInfo = &reflect.XXXStructDescrImpl{
    Name:      "PackageInfo",
    Pkg:       XXXMappingPackageInfo.Pkg,
    Path:      XXXMappingPackageInfo.Path,
    Mapping:   XXXMappingPackageInfo,
    FieldList: []reflect.FieldDescr {
        
        reflect.XXXFieldDescrImpl{
            FD:  XXXMappingPackageInfo.Fields[0],  
        }, 
        
        reflect.XXXFieldDescrImpl{
            FD:  XXXMappingPackageInfo.Fields[1],
            SD: XXXStructDescrServiceInfo,  
        },  
    },
}

var XXXStructDescrServiceInfo = &reflect.XXXStructDescrImpl{
    Name:      "ServiceInfo",
    Pkg:       XXXMappingServiceInfo.Pkg,
    Path:      XXXMappingServiceInfo.Path,
    Mapping:   XXXMappingServiceInfo,
    FieldList: []reflect.FieldDescr {
        
        reflect.XXXFieldDescrImpl{
            FD:  XXXMappingServiceInfo.Fields[0],  
        }, 
        
        reflect.XXXFieldDescrImpl{
            FD:  XXXMappingServiceInfo.Fields[1],
            SD: XXXStructDescrMethodInfo,  
        },  
    },
}

var XXXStructDescrs = map[string]*reflect.XXXStructDescrImpl{
    "GetMethodInfoRequest":  XXXStructDescrGetMethodInfoRequest,
    "GetMethodInfoResponse":  XXXStructDescrGetMethodInfoResponse,
    "GetServiceInfoRequest":  XXXStructDescrGetServiceInfoRequest,
    "GetServiceInfoResponse":  XXXStructDescrGetServiceInfoResponse,
    "ListServicesRequest":  XXXStructDescrListServicesRequest,
    "ListServicesResponse":  XXXStructDescrListServicesResponse,
    "MethodInfo":  XXXStructDescrMethodInfo,
    "PackageInfo":  XXXStructDescrPackageInfo,
    "ServiceInfo":  XXXStructDescrServiceInfo,
}

// Deprecated: No deprecated, but shouldn't be used directly or show up in documentation.
var XXXPackageDescr reflect.PackageDescr = &reflect.XXXPackageDescrImpl{
    Name: "reflection",
    Path: "github.com/bearlytools/claw/rpc/reflection",
    ImportDescrs: []reflect.PackageDescr {
        msgs.XXXPackageDescr,
    },
    StructsDescrs: reflect.XXXStructDescrsImpl{
        Descrs: []reflect.StructDescr{
            XXXStructDescrGetMethodInfoRequest,
            XXXStructDescrGetMethodInfoResponse,
            XXXStructDescrGetServiceInfoRequest,
            XXXStructDescrGetServiceInfoResponse,
            XXXStructDescrListServicesRequest,
            XXXStructDescrListServicesResponse,
            XXXStructDescrMethodInfo,
            XXXStructDescrPackageInfo,
            XXXStructDescrServiceInfo,
        },
    },
}

// PackageDescr returns a PackageDescr for this package.
func PackageDescr() reflect.PackageDescr {
    return XXXPackageDescr
}

// Registers our package description with the runtime.
func init() {
    runtime.RegisterPackage(XXXPackageDescr)

    // Register each struct type by its hash for Any field decoding.
    runtime.RegisterTypeHash(XXXTypeHashGetMethodInfoRequest, runtime.TypeEntry{
        Name:     "GetMethodInfoRequest",
        FullPath: "github.com/bearlytools/claw/rpc/reflection",
        New: func(ctx context.Context) runtime.AnyType {
            return NewGetMethodInfoRequest(ctx)
        },
    })
    runtime.RegisterTypeHash(XXXTypeHashGetMethodInfoResponse, runtime.TypeEntry{
        Name:     "GetMethodInfoResponse",
        FullPath: "github.com/bearlytools/claw/rpc/reflection",
        New: func(ctx context.Context) runtime.AnyType {
            return NewGetMethodInfoResponse(ctx)
        },
    })
    runtime.RegisterTypeHash(XXXTypeHashGetServiceInfoRequest, runtime.TypeEntry{
        Name:     "GetServiceInfoRequest",
        FullPath: "github.com/bearlytools/claw/rpc/reflection",
        New: func(ctx context.Context) runtime.AnyType {
            return NewGetServiceInfoRequest(ctx)
        },
    })
    runtime.RegisterTypeHash(XXXTypeHashGetServiceInfoResponse, runtime.TypeEntry{
        Name:     "GetServiceInfoResponse",
        FullPath: "github.com/bearlytools/claw/rpc/reflection",
        New: func(ctx context.Context) runtime.AnyType {
            return NewGetServiceInfoResponse(ctx)
        },
    })
    runtime.RegisterTypeHash(XXXTypeHashListServicesRequest, runtime.TypeEntry{
        Name:     "ListServicesRequest",
        FullPath: "github.com/bearlytools/claw/rpc/reflection",
        New: func(ctx context.Context) runtime.AnyType {
            return NewListServicesRequest(ctx)
        },
    })
    runtime.RegisterTypeHash(XXXTypeHashListServicesResponse, runtime.TypeEntry{
        Name:     "ListServicesResponse",
        FullPath: "github.com/bearlytools/claw/rpc/reflection",
        New: func(ctx context.Context) runtime.AnyType {
            return NewListServicesResponse(ctx)
        },
    })
    runtime.RegisterTypeHash(XXXTypeHashMethodInfo, runtime.TypeEntry{
        Name:     "MethodInfo",
        FullPath: "github.com/bearlytools/claw/rpc/reflection",
        New: func(ctx context.Context) runtime.AnyType {
            return NewMethodInfo(ctx)
        },
    })
    runtime.RegisterTypeHash(XXXTypeHashPackageInfo, runtime.TypeEntry{
        Name:     "PackageInfo",
        FullPath: "github.com/bearlytools/claw/rpc/reflection",
        New: func(ctx context.Context) runtime.AnyType {
            return NewPackageInfo(ctx)
        },
    })
    runtime.RegisterTypeHash(XXXTypeHashServiceInfo, runtime.TypeEntry{
        Name:     "ServiceInfo",
        FullPath: "github.com/bearlytools/claw/rpc/reflection",
        New: func(ctx context.Context) runtime.AnyType {
            return NewServiceInfo(ctx)
        },
    })
}
