// DO NOT EDIT
// This package is autogenerated and should not be modified except by the clawc compiler.

// Package any
package any

import (
    "context"
    "io"
    "bytes"
    "fmt"

    "github.com/bearlytools/claw/clawc/languages/go/mapping"
    "github.com/bearlytools/claw/languages/go/reflect"
    "github.com/bearlytools/claw/languages/go/reflect/runtime"
    "github.com/bearlytools/claw/clawc/languages/go/segment"
    "github.com/bearlytools/claw/clawc/languages/go/field"
    
)

// Ensure imports are used.
var (
    _ context.Context
    _ = io.EOF
    _ = bytes.MinRead
    _ = fmt.Errorf
    _ mapping.Map
    _ reflect.StructDescr
    _ = runtime.RegisterPackage
    _ segment.Struct
    _ = field.FTBool
)

// SyntaxVersion is the major version of the Claw language that is being rendered.
const SyntaxVersion = 0

var _package = "any"
var _packagePath = "github.com/bearlytools/claw/testing/any/claw"




// Container holds an Any field that can contain any Struct type
type Container struct {
   s *segment.Struct
}

// NewContainer creates a new pooled instance of Container.
// Call Release() when done to return it to the pool for reuse.
func NewContainer(ctx context.Context) Container {
    s := segment.New(ctx, XXXMappingContainer)
    s.SetIsSetEnabled(true)
    return Container{
        s: s,
    }
}

// Release returns the struct to the pool for reuse.
// After calling Release, the struct should not be used.
func (x Container) Release(ctx context.Context) {
    x.s.Release(ctx)
}

// XXXNewContainerFrom creates a new Container from our internal Struct representation.
// As with all things marked XXX*, this should not be used and has not compatibility
// guarantees.
//
// Deprecated: This is not actually deprecated, but it should not be used directly nor
// show up in any documentation.
func XXXNewContainerFrom(s *segment.Struct) Container {
    return Container{s: s}
}

// Marshal marshal's the Struct to []byte. The returned slice is shared by Struct,
// so Struct must not be modified after this call. If Struct needs to be modified,
// use MarshalSafe() instead.
func (x Container) Marshal() ([]byte, error) {
    return x.s.Marshal()
}

// MarshalSafe marshal's the Struct to []byte. The returned slice is a copy
// and safe to modify.
func (x Container) MarshalSafe() ([]byte, error) {
    return x.s.MarshalSafe()
}

// MarshalWriter marshals to an io.Writer.
func (x Container) MarshalWriter(w io.Writer) (n int, err error) {
    return x.s.MarshalWriter(w)
}

// Unmarshal unmarshals b into the Struct.
func (x Container) Unmarshal(b []byte) error {
    return x.s.Unmarshal(b)
}

// UnmarshalReader unmarshals a Struct from an io.Reader.
func (x Container) UnmarshalReader (r io.Reader) (int, error) {
    return x.s.UnmarshalReader(r)
}

func (x Container) Name() string {
    return segment.GetString(x.s, 0)
}

func (x Container) SetName(value string) Container {
    segment.SetString(x.s, 0, value)
    return x
}
func (x Container) IsSetName() bool{
    return x.s.HasField(0)
}

// Data decodes the Any field into the provided target.
// The target must be a pointer to a Claw struct that implements segment.TypeHasher.
// Returns an error if the field is not set, the target doesn't implement required interfaces,
// or the type hash doesn't match.
func (x Container) Data(target any) error {
    return segment.GetAny(x.s, 1, target)
}

// DataRaw returns the raw bytes and type hash without decoding.
// Useful for forwarding/proxying scenarios.
// Returns (nil, empty hash, false) if the field is not set.
func (x Container) DataRaw() (data []byte, typeHash [16]byte, ok bool) {
    return segment.GetAnyRaw(x.s, 1)
}

// SetData sets the Any field with a Claw struct value.
// The value must implement segment.TypeHasher and segment.StructGetter interfaces.
func (x Container) SetData(value any) error {
    return segment.SetAny(x.s, 1, value)
}

// SetDataRaw sets the Any field from raw bytes and type hash.
// Used by Ingest to reconstitute Any fields from Walk tokens.
func (x Container) SetDataRaw(rawData, typeHash []byte) error {
    return segment.SetAnyRaw(x.s, 1, rawData, typeHash)
}
func (x Container) IsSetData() bool{
    return x.s.HasField(1)
}



// ClawStruct returns a reflection type representing the Struct.
func (x Container) ClawStruct() reflect.Struct{
    return reflect.XXXNewStruct(x.s, x.XXXDescr())
}

// XXXGetStruct returns the internal Struct representation. Like all XXX* types/methods,
// this should not be used and has no compatibility guarantees.
//
// Deprecated: Not deprectated, but should not be used and should not show up in documentation.
func (x Container) XXXGetStruct() *segment.Struct {
    return x.s
}

// XXXTypeHash returns the SHAKE128 hash (128 bits) of this type's identity.
// Used for Any type serialization to identify the concrete type.
//
// Deprecated: Not deprecated, but should not be used directly and should not show up in documentation.
func (x Container) XXXTypeHash() [16]byte {
    return XXXTypeHashContainer
}

// SetRecording enables or disables mutation recording for patch generation.
// When enabled, all Set* operations and list mutations are recorded.
func (x Container) SetRecording(enabled bool) Container {
    x.s.SetRecording(enabled)
    return x
}

// Recording returns whether mutation recording is enabled.
func (x Container) Recording() bool {
    return x.s.Recording()
}

// DrainRecordedOps returns all recorded operations since recording was enabled
// (or since the last DrainRecordedOps call) and clears the internal list.
// Use patch.NewPatchFromOps() to convert these to a Patch for application.
func (x Container) DrainRecordedOps() []segment.RecordedOp {
    return x.s.DrainRecordedOps()
}

// RecordedOpsLen returns the number of recorded operations.
func (x Container) RecordedOpsLen() int {
    return x.s.RecordedOpsLen()
}

// ContainerRaw is a plain Go struct representation of Container.
// Zero values are not set (sparse encoding).
type ContainerRaw struct {
    Name string
    Data any
}

// NewContainerFromRaw creates a new Container from a Raw struct representation.
// Only non-zero values are set (sparse encoding).
func NewContainerFromRaw(ctx context.Context, raw ContainerRaw) Container {
    x := NewContainer(ctx)
    if raw.Name != "" {
        x.SetName(raw.Name)
    }
    return x
}

// ToRaw converts the struct to a plain Go struct representation.
func (x Container) ToRaw(ctx context.Context) ContainerRaw {
    raw := ContainerRaw{}
    raw.Name = x.Name()
    return raw
}
 

// XXXDescr returns the Struct's descriptor. This should only be used
// by the reflect package and is has no compatibility promises like all XXX fields.
//
// Deprecated: No deprecated, but shouldn't be used directly or show up in documentation.
func (x Container) XXXDescr() reflect.StructDescr {
    return XXXPackageDescr.Structs().Get(0)
}

// Inner is a simple struct to be stored in Any fields
type Inner struct {
   s *segment.Struct
}

// NewInner creates a new pooled instance of Inner.
// Call Release() when done to return it to the pool for reuse.
func NewInner(ctx context.Context) Inner {
    s := segment.New(ctx, XXXMappingInner)
    s.SetIsSetEnabled(true)
    return Inner{
        s: s,
    }
}

// Release returns the struct to the pool for reuse.
// After calling Release, the struct should not be used.
func (x Inner) Release(ctx context.Context) {
    x.s.Release(ctx)
}

// XXXNewInnerFrom creates a new Inner from our internal Struct representation.
// As with all things marked XXX*, this should not be used and has not compatibility
// guarantees.
//
// Deprecated: This is not actually deprecated, but it should not be used directly nor
// show up in any documentation.
func XXXNewInnerFrom(s *segment.Struct) Inner {
    return Inner{s: s}
}

// Marshal marshal's the Struct to []byte. The returned slice is shared by Struct,
// so Struct must not be modified after this call. If Struct needs to be modified,
// use MarshalSafe() instead.
func (x Inner) Marshal() ([]byte, error) {
    return x.s.Marshal()
}

// MarshalSafe marshal's the Struct to []byte. The returned slice is a copy
// and safe to modify.
func (x Inner) MarshalSafe() ([]byte, error) {
    return x.s.MarshalSafe()
}

// MarshalWriter marshals to an io.Writer.
func (x Inner) MarshalWriter(w io.Writer) (n int, err error) {
    return x.s.MarshalWriter(w)
}

// Unmarshal unmarshals b into the Struct.
func (x Inner) Unmarshal(b []byte) error {
    return x.s.Unmarshal(b)
}

// UnmarshalReader unmarshals a Struct from an io.Reader.
func (x Inner) UnmarshalReader (r io.Reader) (int, error) {
    return x.s.UnmarshalReader(r)
}

func (x Inner) ID() int64 {
    return segment.GetInt64(x.s, 0)
}

func (x Inner) SetID(value int64) Inner {
    segment.SetInt64(x.s, 0, value)
    return x
}
func (x Inner) IsSetID() bool{
    return x.s.HasField(0)
}

func (x Inner) Value() string {
    return segment.GetString(x.s, 1)
}

func (x Inner) SetValue(value string) Inner {
    segment.SetString(x.s, 1, value)
    return x
}
func (x Inner) IsSetValue() bool{
    return x.s.HasField(1)
}



// ClawStruct returns a reflection type representing the Struct.
func (x Inner) ClawStruct() reflect.Struct{
    return reflect.XXXNewStruct(x.s, x.XXXDescr())
}

// XXXGetStruct returns the internal Struct representation. Like all XXX* types/methods,
// this should not be used and has no compatibility guarantees.
//
// Deprecated: Not deprectated, but should not be used and should not show up in documentation.
func (x Inner) XXXGetStruct() *segment.Struct {
    return x.s
}

// XXXTypeHash returns the SHAKE128 hash (128 bits) of this type's identity.
// Used for Any type serialization to identify the concrete type.
//
// Deprecated: Not deprecated, but should not be used directly and should not show up in documentation.
func (x Inner) XXXTypeHash() [16]byte {
    return XXXTypeHashInner
}

// SetRecording enables or disables mutation recording for patch generation.
// When enabled, all Set* operations and list mutations are recorded.
func (x Inner) SetRecording(enabled bool) Inner {
    x.s.SetRecording(enabled)
    return x
}

// Recording returns whether mutation recording is enabled.
func (x Inner) Recording() bool {
    return x.s.Recording()
}

// DrainRecordedOps returns all recorded operations since recording was enabled
// (or since the last DrainRecordedOps call) and clears the internal list.
// Use patch.NewPatchFromOps() to convert these to a Patch for application.
func (x Inner) DrainRecordedOps() []segment.RecordedOp {
    return x.s.DrainRecordedOps()
}

// RecordedOpsLen returns the number of recorded operations.
func (x Inner) RecordedOpsLen() int {
    return x.s.RecordedOpsLen()
}

// InnerRaw is a plain Go struct representation of Inner.
// Zero values are not set (sparse encoding).
type InnerRaw struct {
    ID int64
    Value string
}

// NewInnerFromRaw creates a new Inner from a Raw struct representation.
// Only non-zero values are set (sparse encoding).
func NewInnerFromRaw(ctx context.Context, raw InnerRaw) Inner {
    x := NewInner(ctx)
    if raw.ID != 0 {
        x.SetID(raw.ID)
    }
    if raw.Value != "" {
        x.SetValue(raw.Value)
    }
    return x
}

// ToRaw converts the struct to a plain Go struct representation.
func (x Inner) ToRaw(ctx context.Context) InnerRaw {
    raw := InnerRaw{}
    raw.ID = x.ID()
    raw.Value = x.Value()
    return raw
}
 

// XXXDescr returns the Struct's descriptor. This should only be used
// by the reflect package and is has no compatibility promises like all XXX fields.
//
// Deprecated: No deprecated, but shouldn't be used directly or show up in documentation.
func (x Inner) XXXDescr() reflect.StructDescr {
    return XXXPackageDescr.Structs().Get(1)
}

// ListContainer holds a []Any field for multiple values of different types
type ListContainer struct {
   s *segment.Struct
}

// NewListContainer creates a new pooled instance of ListContainer.
// Call Release() when done to return it to the pool for reuse.
func NewListContainer(ctx context.Context) ListContainer {
    s := segment.New(ctx, XXXMappingListContainer)
    s.SetIsSetEnabled(true)
    return ListContainer{
        s: s,
    }
}

// Release returns the struct to the pool for reuse.
// After calling Release, the struct should not be used.
func (x ListContainer) Release(ctx context.Context) {
    x.s.Release(ctx)
}

// XXXNewListContainerFrom creates a new ListContainer from our internal Struct representation.
// As with all things marked XXX*, this should not be used and has not compatibility
// guarantees.
//
// Deprecated: This is not actually deprecated, but it should not be used directly nor
// show up in any documentation.
func XXXNewListContainerFrom(s *segment.Struct) ListContainer {
    return ListContainer{s: s}
}

// Marshal marshal's the Struct to []byte. The returned slice is shared by Struct,
// so Struct must not be modified after this call. If Struct needs to be modified,
// use MarshalSafe() instead.
func (x ListContainer) Marshal() ([]byte, error) {
    return x.s.Marshal()
}

// MarshalSafe marshal's the Struct to []byte. The returned slice is a copy
// and safe to modify.
func (x ListContainer) MarshalSafe() ([]byte, error) {
    return x.s.MarshalSafe()
}

// MarshalWriter marshals to an io.Writer.
func (x ListContainer) MarshalWriter(w io.Writer) (n int, err error) {
    return x.s.MarshalWriter(w)
}

// Unmarshal unmarshals b into the Struct.
func (x ListContainer) Unmarshal(b []byte) error {
    return x.s.Unmarshal(b)
}

// UnmarshalReader unmarshals a Struct from an io.Reader.
func (x ListContainer) UnmarshalReader (r io.Reader) (int, error) {
    return x.s.UnmarshalReader(r)
}

func (x ListContainer) Name() string {
    return segment.GetString(x.s, 0)
}

func (x ListContainer) SetName(value string) ListContainer {
    segment.SetString(x.s, 0, value)
    return x
}
func (x ListContainer) IsSetName() bool{
    return x.s.HasField(0)
}

// ItemsLen returns the number of items in the []Any field.
func (x ListContainer) ItemsLen() int {
    return segment.GetListAnyLen(x.s, 1)
}

// ItemsGet decodes an item from the []Any field into the provided target.
// The target must be a pointer to a Claw struct that implements segment.TypeHasher.
func (x ListContainer) ItemsGet(index int, target any) error {
    return segment.GetListAny(x.s, 1, index, target)
}

// ItemsGetRaw returns the raw bytes and type hash of an item without decoding.
// Useful for forwarding/proxying scenarios.
func (x ListContainer) ItemsGetRaw(index int) (data []byte, typeHash [16]byte, ok bool) {
    return segment.GetListAnyRaw(x.s, 1, index)
}

// SetItems sets the []Any field with a slice of Claw struct values.
// Each value must implement segment.TypeHasher and segment.StructGetter interfaces.
func (x ListContainer) SetItems(values []any) error {
    return segment.SetListAny(x.s, 1, values)
}

// SetItemsRaw sets the []Any field from raw bytes and type hashes.
// Used by Ingest to reconstitute []Any fields from Walk tokens.
func (x ListContainer) SetItemsRaw(items []segment.AnyRawItem) error {
    return segment.SetListAnyRaw(x.s, 1, items)
}
func (x ListContainer) IsSetItems() bool{
    return x.s.HasField(1)
}



// ClawStruct returns a reflection type representing the Struct.
func (x ListContainer) ClawStruct() reflect.Struct{
    return reflect.XXXNewStruct(x.s, x.XXXDescr())
}

// XXXGetStruct returns the internal Struct representation. Like all XXX* types/methods,
// this should not be used and has no compatibility guarantees.
//
// Deprecated: Not deprectated, but should not be used and should not show up in documentation.
func (x ListContainer) XXXGetStruct() *segment.Struct {
    return x.s
}

// XXXTypeHash returns the SHAKE128 hash (128 bits) of this type's identity.
// Used for Any type serialization to identify the concrete type.
//
// Deprecated: Not deprecated, but should not be used directly and should not show up in documentation.
func (x ListContainer) XXXTypeHash() [16]byte {
    return XXXTypeHashListContainer
}

// SetRecording enables or disables mutation recording for patch generation.
// When enabled, all Set* operations and list mutations are recorded.
func (x ListContainer) SetRecording(enabled bool) ListContainer {
    x.s.SetRecording(enabled)
    return x
}

// Recording returns whether mutation recording is enabled.
func (x ListContainer) Recording() bool {
    return x.s.Recording()
}

// DrainRecordedOps returns all recorded operations since recording was enabled
// (or since the last DrainRecordedOps call) and clears the internal list.
// Use patch.NewPatchFromOps() to convert these to a Patch for application.
func (x ListContainer) DrainRecordedOps() []segment.RecordedOp {
    return x.s.DrainRecordedOps()
}

// RecordedOpsLen returns the number of recorded operations.
func (x ListContainer) RecordedOpsLen() int {
    return x.s.RecordedOpsLen()
}

// ListContainerRaw is a plain Go struct representation of ListContainer.
// Zero values are not set (sparse encoding).
type ListContainerRaw struct {
    Name string
    Items []any
}

// NewListContainerFromRaw creates a new ListContainer from a Raw struct representation.
// Only non-zero values are set (sparse encoding).
func NewListContainerFromRaw(ctx context.Context, raw ListContainerRaw) ListContainer {
    x := NewListContainer(ctx)
    if raw.Name != "" {
        x.SetName(raw.Name)
    }
    return x
}

// ToRaw converts the struct to a plain Go struct representation.
func (x ListContainer) ToRaw(ctx context.Context) ListContainerRaw {
    raw := ListContainerRaw{}
    raw.Name = x.Name()
    return raw
}
 

// XXXDescr returns the Struct's descriptor. This should only be used
// by the reflect package and is has no compatibility promises like all XXX fields.
//
// Deprecated: No deprecated, but shouldn't be used directly or show up in documentation.
func (x ListContainer) XXXDescr() reflect.StructDescr {
    return XXXPackageDescr.Structs().Get(2)
}

// Outer is a more complex struct to test nested Any
type Outer struct {
   s *segment.Struct
}

// NewOuter creates a new pooled instance of Outer.
// Call Release() when done to return it to the pool for reuse.
func NewOuter(ctx context.Context) Outer {
    s := segment.New(ctx, XXXMappingOuter)
    s.SetIsSetEnabled(true)
    return Outer{
        s: s,
    }
}

// Release returns the struct to the pool for reuse.
// After calling Release, the struct should not be used.
func (x Outer) Release(ctx context.Context) {
    x.s.Release(ctx)
}

// XXXNewOuterFrom creates a new Outer from our internal Struct representation.
// As with all things marked XXX*, this should not be used and has not compatibility
// guarantees.
//
// Deprecated: This is not actually deprecated, but it should not be used directly nor
// show up in any documentation.
func XXXNewOuterFrom(s *segment.Struct) Outer {
    return Outer{s: s}
}

// Marshal marshal's the Struct to []byte. The returned slice is shared by Struct,
// so Struct must not be modified after this call. If Struct needs to be modified,
// use MarshalSafe() instead.
func (x Outer) Marshal() ([]byte, error) {
    return x.s.Marshal()
}

// MarshalSafe marshal's the Struct to []byte. The returned slice is a copy
// and safe to modify.
func (x Outer) MarshalSafe() ([]byte, error) {
    return x.s.MarshalSafe()
}

// MarshalWriter marshals to an io.Writer.
func (x Outer) MarshalWriter(w io.Writer) (n int, err error) {
    return x.s.MarshalWriter(w)
}

// Unmarshal unmarshals b into the Struct.
func (x Outer) Unmarshal(b []byte) error {
    return x.s.Unmarshal(b)
}

// UnmarshalReader unmarshals a Struct from an io.Reader.
func (x Outer) UnmarshalReader (r io.Reader) (int, error) {
    return x.s.UnmarshalReader(r)
}

func (x Outer) Label() string {
    return segment.GetString(x.s, 0)
}

func (x Outer) SetLabel(value string) Outer {
    segment.SetString(x.s, 0, value)
    return x
}
func (x Outer) IsSetLabel() bool{
    return x.s.HasField(0)
}

func (x Outer) Count() int32 {
    return segment.GetInt32(x.s, 1)
}

func (x Outer) SetCount(value int32) Outer {
    segment.SetInt32(x.s, 1, value)
    return x
}
func (x Outer) IsSetCount() bool{
    return x.s.HasField(1)
}

func (x Outer) Nested() Inner {
    s := segment.GetNestedStruct(x.s, 2, XXXMappingInner)
    return Inner{s: s}
}

func (x Outer) SetNested(value Inner) Outer {
    segment.SetNestedStruct(x.s, 2, value.XXXGetStruct())
    return x
}
func (x Outer) IsSetNested() bool{
    return x.s.HasField(2)
}



// ClawStruct returns a reflection type representing the Struct.
func (x Outer) ClawStruct() reflect.Struct{
    return reflect.XXXNewStruct(x.s, x.XXXDescr())
}

// XXXGetStruct returns the internal Struct representation. Like all XXX* types/methods,
// this should not be used and has no compatibility guarantees.
//
// Deprecated: Not deprectated, but should not be used and should not show up in documentation.
func (x Outer) XXXGetStruct() *segment.Struct {
    return x.s
}

// XXXTypeHash returns the SHAKE128 hash (128 bits) of this type's identity.
// Used for Any type serialization to identify the concrete type.
//
// Deprecated: Not deprecated, but should not be used directly and should not show up in documentation.
func (x Outer) XXXTypeHash() [16]byte {
    return XXXTypeHashOuter
}

// SetRecording enables or disables mutation recording for patch generation.
// When enabled, all Set* operations and list mutations are recorded.
func (x Outer) SetRecording(enabled bool) Outer {
    x.s.SetRecording(enabled)
    return x
}

// Recording returns whether mutation recording is enabled.
func (x Outer) Recording() bool {
    return x.s.Recording()
}

// DrainRecordedOps returns all recorded operations since recording was enabled
// (or since the last DrainRecordedOps call) and clears the internal list.
// Use patch.NewPatchFromOps() to convert these to a Patch for application.
func (x Outer) DrainRecordedOps() []segment.RecordedOp {
    return x.s.DrainRecordedOps()
}

// RecordedOpsLen returns the number of recorded operations.
func (x Outer) RecordedOpsLen() int {
    return x.s.RecordedOpsLen()
}

// OuterRaw is a plain Go struct representation of Outer.
// Zero values are not set (sparse encoding).
type OuterRaw struct {
    Label string
    Count int32
    Nested *InnerRaw
}

// NewOuterFromRaw creates a new Outer from a Raw struct representation.
// Only non-zero values are set (sparse encoding).
func NewOuterFromRaw(ctx context.Context, raw OuterRaw) Outer {
    x := NewOuter(ctx)
    if raw.Label != "" {
        x.SetLabel(raw.Label)
    }
    if raw.Count != 0 {
        x.SetCount(raw.Count)
    }
    if raw.Nested != nil {
        x.SetNested(NewInnerFromRaw(ctx, *raw.Nested))
    }
    return x
}

// ToRaw converts the struct to a plain Go struct representation.
func (x Outer) ToRaw(ctx context.Context) OuterRaw {
    raw := OuterRaw{}
    raw.Label = x.Label()
    raw.Count = x.Count()
    if x.s.HasField(2) {
        nestedRaw := x.Nested().ToRaw(ctx)
        raw.Nested = &nestedRaw
    }
    return raw
}
 

// XXXDescr returns the Struct's descriptor. This should only be used
// by the reflect package and is has no compatibility promises like all XXX fields.
//
// Deprecated: No deprecated, but shouldn't be used directly or show up in documentation.
func (x Outer) XXXDescr() reflect.StructDescr {
    return XXXPackageDescr.Structs().Get(3)
} 

// Everything below this line is internal details.

// Type hash constants for Any type support.
// These are SHAKE128 hashes (128 bits) of the full type path + name.
// Deprecated: Not deprecated, but shouldn't be used directly or show up in documentation.
var XXXTypeHashContainer = [16]byte{0x6e, 0xc1, 0x9c, 0xcb, 0x7d, 0xcb, 0x66, 0x24, 0xf9, 0xa9, 0xa2, 0x20, 0x49, 0x29, 0x5f, 0x3b}

// Deprecated: Not deprecated, but shouldn't be used directly or show up in documentation.
var XXXTypeHashInner = [16]byte{0xfa, 0xe9, 0xe0, 0xca, 0x97, 0x8a, 0xd0, 0x00, 0xa1, 0x18, 0x0f, 0x61, 0x38, 0xd6, 0x92, 0x9f}

// Deprecated: Not deprecated, but shouldn't be used directly or show up in documentation.
var XXXTypeHashListContainer = [16]byte{0xff, 0x8e, 0x38, 0x20, 0xd0, 0x6f, 0x0f, 0x1a, 0xa0, 0x58, 0xc5, 0x94, 0xca, 0x2e, 0x0a, 0x22}

// Deprecated: Not deprecated, but shouldn't be used directly or show up in documentation.
var XXXTypeHashOuter = [16]byte{0xcf, 0xe6, 0x45, 0x63, 0x15, 0xe7, 0x0e, 0x06, 0xc7, 0x3c, 0xc0, 0x07, 0x1c, 0xc3, 0xb5, 0x50}

// Deprecated: Not deprecated, but shouldn't be used directly or show up in documentation.
var XXXMappingContainer = &mapping.Map{
    Name: "Container",
    Pkg: "any",
    Path: "github.com/bearlytools/claw/testing/any/claw",
    Fields: []*mapping.FieldDescr{
        {
            Name: "Name",
            Type: field.FTString,
            Package: "any",
            FullPath: "github.com/bearlytools/claw/testing/any/claw",
            FieldNum: 0,
            IsEnum: false,
            IsAny: false,
        },
        {
            Name: "Data",
            Type: field.FTAny,
            Package: "any",
            FullPath: "github.com/bearlytools/claw/testing/any/claw",
            FieldNum: 1,
            IsEnum: false,
            IsAny: true,
        },
    },
}

// Deprecated: Not deprecated, but shouldn't be used directly or show up in documentation.
var XXXMappingInner = &mapping.Map{
    Name: "Inner",
    Pkg: "any",
    Path: "github.com/bearlytools/claw/testing/any/claw",
    Fields: []*mapping.FieldDescr{
        {
            Name: "ID",
            Type: field.FTInt64,
            Package: "any",
            FullPath: "github.com/bearlytools/claw/testing/any/claw",
            FieldNum: 0,
            IsEnum: false,
            IsAny: false,
        },
        {
            Name: "Value",
            Type: field.FTString,
            Package: "any",
            FullPath: "github.com/bearlytools/claw/testing/any/claw",
            FieldNum: 1,
            IsEnum: false,
            IsAny: false,
        },
    },
}

// Deprecated: Not deprecated, but shouldn't be used directly or show up in documentation.
var XXXMappingListContainer = &mapping.Map{
    Name: "ListContainer",
    Pkg: "any",
    Path: "github.com/bearlytools/claw/testing/any/claw",
    Fields: []*mapping.FieldDescr{
        {
            Name: "Name",
            Type: field.FTString,
            Package: "any",
            FullPath: "github.com/bearlytools/claw/testing/any/claw",
            FieldNum: 0,
            IsEnum: false,
            IsAny: false,
        },
        {
            Name: "Items",
            Type: field.FTListAny,
            Package: "any",
            FullPath: "github.com/bearlytools/claw/testing/any/claw",
            FieldNum: 1,
            IsEnum: false,
            IsAny: true,
        },
    },
}

// Deprecated: Not deprecated, but shouldn't be used directly or show up in documentation.
var XXXMappingOuter = &mapping.Map{
    Name: "Outer",
    Pkg: "any",
    Path: "github.com/bearlytools/claw/testing/any/claw",
    Fields: []*mapping.FieldDescr{
        {
            Name: "Label",
            Type: field.FTString,
            Package: "any",
            FullPath: "github.com/bearlytools/claw/testing/any/claw",
            FieldNum: 0,
            IsEnum: false,
            IsAny: false,
        },
        {
            Name: "Count",
            Type: field.FTInt32,
            Package: "any",
            FullPath: "github.com/bearlytools/claw/testing/any/claw",
            FieldNum: 1,
            IsEnum: false,
            IsAny: false,
        },
        {
            Name: "Nested",
            Type: field.FTStruct,
            Package: "any",
            FullPath: "github.com/bearlytools/claw/testing/any/claw",
            FieldNum: 2,
            IsEnum: false,
            IsAny: false,
            StructName: "Inner",
            
            Mapping: XXXMappingInner,
        },
    },
}


// init initializes all mapping function pointer tables for O(1) dispatch.
func init() {
    XXXMappingContainer.Init()
    XXXMappingInner.Init()
    XXXMappingListContainer.Init()
    XXXMappingOuter.Init()
}

 


var XXXStructDescrContainer = &reflect.XXXStructDescrImpl{
    Name:      "Container",
    Pkg:       XXXMappingContainer.Pkg,
    Path:      XXXMappingContainer.Path,
    Mapping:   XXXMappingContainer,
    FieldList: []reflect.FieldDescr {
        
        reflect.XXXFieldDescrImpl{
            FD:  XXXMappingContainer.Fields[0],  
        }, 
        
        reflect.XXXFieldDescrImpl{
            FD:  XXXMappingContainer.Fields[1],  
        },  
    },
}

var XXXStructDescrInner = &reflect.XXXStructDescrImpl{
    Name:      "Inner",
    Pkg:       XXXMappingInner.Pkg,
    Path:      XXXMappingInner.Path,
    Mapping:   XXXMappingInner,
    FieldList: []reflect.FieldDescr {
        
        reflect.XXXFieldDescrImpl{
            FD:  XXXMappingInner.Fields[0],  
        }, 
        
        reflect.XXXFieldDescrImpl{
            FD:  XXXMappingInner.Fields[1],  
        },  
    },
}

var XXXStructDescrListContainer = &reflect.XXXStructDescrImpl{
    Name:      "ListContainer",
    Pkg:       XXXMappingListContainer.Pkg,
    Path:      XXXMappingListContainer.Path,
    Mapping:   XXXMappingListContainer,
    FieldList: []reflect.FieldDescr {
        
        reflect.XXXFieldDescrImpl{
            FD:  XXXMappingListContainer.Fields[0],  
        }, 
        
        reflect.XXXFieldDescrImpl{
            FD:  XXXMappingListContainer.Fields[1],  
        },  
    },
}

var XXXStructDescrOuter = &reflect.XXXStructDescrImpl{
    Name:      "Outer",
    Pkg:       XXXMappingOuter.Pkg,
    Path:      XXXMappingOuter.Path,
    Mapping:   XXXMappingOuter,
    FieldList: []reflect.FieldDescr {
        
        reflect.XXXFieldDescrImpl{
            FD:  XXXMappingOuter.Fields[0],  
        }, 
        
        reflect.XXXFieldDescrImpl{
            FD:  XXXMappingOuter.Fields[1],  
        }, 
        
        reflect.XXXFieldDescrImpl{
            FD:  XXXMappingOuter.Fields[2],
            SD: XXXStructDescrInner,  
        },  
    },
}

var XXXStructDescrs = map[string]*reflect.XXXStructDescrImpl{
    "Container":  XXXStructDescrContainer,
    "Inner":  XXXStructDescrInner,
    "ListContainer":  XXXStructDescrListContainer,
    "Outer":  XXXStructDescrOuter,
}

// Deprecated: No deprecated, but shouldn't be used directly or show up in documentation.
var XXXPackageDescr reflect.PackageDescr = &reflect.XXXPackageDescrImpl{
    Name: "any",
    Path: "github.com/bearlytools/claw/testing/any/claw",
    StructsDescrs: reflect.XXXStructDescrsImpl{
        Descrs: []reflect.StructDescr{
            XXXStructDescrContainer,
            XXXStructDescrInner,
            XXXStructDescrListContainer,
            XXXStructDescrOuter,
        },
    },
}

// PackageDescr returns a PackageDescr for this package.
func PackageDescr() reflect.PackageDescr {
    return XXXPackageDescr
}

// Registers our package description with the runtime.
func init() {
    runtime.RegisterPackage(XXXPackageDescr)

    // Register each struct type by its hash for Any field decoding.
    runtime.RegisterTypeHash(XXXTypeHashContainer, runtime.TypeEntry{
        Name:     "Container",
        FullPath: "github.com/bearlytools/claw/testing/any/claw",
        New: func(ctx context.Context) runtime.AnyType {
            return NewContainer(ctx)
        },
    })
    runtime.RegisterTypeHash(XXXTypeHashInner, runtime.TypeEntry{
        Name:     "Inner",
        FullPath: "github.com/bearlytools/claw/testing/any/claw",
        New: func(ctx context.Context) runtime.AnyType {
            return NewInner(ctx)
        },
    })
    runtime.RegisterTypeHash(XXXTypeHashListContainer, runtime.TypeEntry{
        Name:     "ListContainer",
        FullPath: "github.com/bearlytools/claw/testing/any/claw",
        New: func(ctx context.Context) runtime.AnyType {
            return NewListContainer(ctx)
        },
    })
    runtime.RegisterTypeHash(XXXTypeHashOuter, runtime.TypeEntry{
        Name:     "Outer",
        FullPath: "github.com/bearlytools/claw/testing/any/claw",
        New: func(ctx context.Context) runtime.AnyType {
            return NewOuter(ctx)
        },
    })
}
