// DO NOT EDIT
// This package is autogenerated and should not be modified except by the clawc compiler.

package any

import (
    "context"
    "fmt"

    "github.com/bearlytools/claw/clawc/languages/go/clawiter"
    "github.com/bearlytools/claw/clawc/languages/go/field"
    "github.com/bearlytools/claw/clawc/languages/go/segment"
)

// Ensure imports are used.
var _ context.Context
var _ = fmt.Errorf
var _ = field.FTBool
var _ segment.AnyRawItem


// Ingest populates the struct from a Walker with options.
// This is the inverse of Walk().
func (x *Container) Ingest(ctx context.Context, walk clawiter.Walker, opts ...clawiter.IngestOption) error {
    // Apply options
    var o clawiter.IngestOptions
    for _, opt := range opts {
        var err error
        o, err = opt(o)
        if err != nil {
            return err
        }
    }

    // Convert Walker to iter.Seq for TokenStream
    seq := func(yield func(clawiter.Token) bool) {
        walk(yield)
    }
    ts := clawiter.NewTokenStream(seq)
    defer ts.Close()
    return x.XXXIngestFrom(ctx, ts, o)
}

// XXXIngestFrom is for internal use - ingests from a shared token stream.
func (x *Container) XXXIngestFrom(ctx context.Context, ts *clawiter.TokenStream, opts clawiter.IngestOptions) error {
    tok, ok := ts.Next()
    if !ok {
        return fmt.Errorf("expected TokenStructStart, got EOF")
    }
    if tok.Kind != clawiter.TokenStructStart {
        return fmt.Errorf("expected TokenStructStart, got %v", tok.Kind)
    }

    for {
        tok, ok = ts.Next()
        if !ok {
            return fmt.Errorf("unexpected EOF in Container")
        }

        if tok.Kind == clawiter.TokenStructEnd {
            return nil
        }

        if tok.Kind != clawiter.TokenField {
            return fmt.Errorf("expected TokenField, got %v", tok.Kind)
        }

        switch tok.Name {
        case "Name":
            x.SetName(tok.String())
        case "Data":
            if tok.IsNil {
                continue
            }
            if err := x.SetDataRaw(tok.Bytes, tok.TypeHash); err != nil {
                return fmt.Errorf("ingesting Data: %w", err)
            }
        default:
            if opts.IgnoreUnknownFields {
                if err := clawiter.SkipValue(ts, tok); err != nil {
                    return err
                }
                continue
            }
            return fmt.Errorf("unknown field: %s", tok.Name)
        }
    }
}

// Ingest populates the struct from a Walker with options.
// This is the inverse of Walk().
func (x *Inner) Ingest(ctx context.Context, walk clawiter.Walker, opts ...clawiter.IngestOption) error {
    // Apply options
    var o clawiter.IngestOptions
    for _, opt := range opts {
        var err error
        o, err = opt(o)
        if err != nil {
            return err
        }
    }

    // Convert Walker to iter.Seq for TokenStream
    seq := func(yield func(clawiter.Token) bool) {
        walk(yield)
    }
    ts := clawiter.NewTokenStream(seq)
    defer ts.Close()
    return x.XXXIngestFrom(ctx, ts, o)
}

// XXXIngestFrom is for internal use - ingests from a shared token stream.
func (x *Inner) XXXIngestFrom(ctx context.Context, ts *clawiter.TokenStream, opts clawiter.IngestOptions) error {
    tok, ok := ts.Next()
    if !ok {
        return fmt.Errorf("expected TokenStructStart, got EOF")
    }
    if tok.Kind != clawiter.TokenStructStart {
        return fmt.Errorf("expected TokenStructStart, got %v", tok.Kind)
    }

    for {
        tok, ok = ts.Next()
        if !ok {
            return fmt.Errorf("unexpected EOF in Inner")
        }

        if tok.Kind == clawiter.TokenStructEnd {
            return nil
        }

        if tok.Kind != clawiter.TokenField {
            return fmt.Errorf("expected TokenField, got %v", tok.Kind)
        }

        switch tok.Name {
        case "ID":
            x.SetID(tok.Int64())
        case "Value":
            x.SetValue(tok.String())
        default:
            if opts.IgnoreUnknownFields {
                if err := clawiter.SkipValue(ts, tok); err != nil {
                    return err
                }
                continue
            }
            return fmt.Errorf("unknown field: %s", tok.Name)
        }
    }
}

// Ingest populates the struct from a Walker with options.
// This is the inverse of Walk().
func (x *ListContainer) Ingest(ctx context.Context, walk clawiter.Walker, opts ...clawiter.IngestOption) error {
    // Apply options
    var o clawiter.IngestOptions
    for _, opt := range opts {
        var err error
        o, err = opt(o)
        if err != nil {
            return err
        }
    }

    // Convert Walker to iter.Seq for TokenStream
    seq := func(yield func(clawiter.Token) bool) {
        walk(yield)
    }
    ts := clawiter.NewTokenStream(seq)
    defer ts.Close()
    return x.XXXIngestFrom(ctx, ts, o)
}

// XXXIngestFrom is for internal use - ingests from a shared token stream.
func (x *ListContainer) XXXIngestFrom(ctx context.Context, ts *clawiter.TokenStream, opts clawiter.IngestOptions) error {
    tok, ok := ts.Next()
    if !ok {
        return fmt.Errorf("expected TokenStructStart, got EOF")
    }
    if tok.Kind != clawiter.TokenStructStart {
        return fmt.Errorf("expected TokenStructStart, got %v", tok.Kind)
    }

    for {
        tok, ok = ts.Next()
        if !ok {
            return fmt.Errorf("unexpected EOF in ListContainer")
        }

        if tok.Kind == clawiter.TokenStructEnd {
            return nil
        }

        if tok.Kind != clawiter.TokenField {
            return fmt.Errorf("expected TokenField, got %v", tok.Kind)
        }

        switch tok.Name {
        case "Name":
            x.SetName(tok.String())
        case "Items":
            if tok.IsNil {
                continue
            }
            listTok, ok := ts.Next()
            if !ok || listTok.Kind != clawiter.TokenListStart {
                return fmt.Errorf("expected TokenListStart for Items")
            }
            var anyItems []segment.AnyRawItem
            for {
                itemTok, ok := ts.Next()
                if !ok {
                    return fmt.Errorf("unexpected EOF in Items list")
                }
                if itemTok.Kind == clawiter.TokenListEnd {
                    break
                }
                anyItems = append(anyItems, segment.AnyRawItem{
                    Data:     itemTok.Bytes,
                    TypeHash: itemTok.TypeHash,
                })
            }
            if err := x.SetItemsRaw(anyItems); err != nil {
                return fmt.Errorf("ingesting Items: %w", err)
            }
        default:
            if opts.IgnoreUnknownFields {
                if err := clawiter.SkipValue(ts, tok); err != nil {
                    return err
                }
                continue
            }
            return fmt.Errorf("unknown field: %s", tok.Name)
        }
    }
}

// Ingest populates the struct from a Walker with options.
// This is the inverse of Walk().
func (x *Outer) Ingest(ctx context.Context, walk clawiter.Walker, opts ...clawiter.IngestOption) error {
    // Apply options
    var o clawiter.IngestOptions
    for _, opt := range opts {
        var err error
        o, err = opt(o)
        if err != nil {
            return err
        }
    }

    // Convert Walker to iter.Seq for TokenStream
    seq := func(yield func(clawiter.Token) bool) {
        walk(yield)
    }
    ts := clawiter.NewTokenStream(seq)
    defer ts.Close()
    return x.XXXIngestFrom(ctx, ts, o)
}

// XXXIngestFrom is for internal use - ingests from a shared token stream.
func (x *Outer) XXXIngestFrom(ctx context.Context, ts *clawiter.TokenStream, opts clawiter.IngestOptions) error {
    tok, ok := ts.Next()
    if !ok {
        return fmt.Errorf("expected TokenStructStart, got EOF")
    }
    if tok.Kind != clawiter.TokenStructStart {
        return fmt.Errorf("expected TokenStructStart, got %v", tok.Kind)
    }

    for {
        tok, ok = ts.Next()
        if !ok {
            return fmt.Errorf("unexpected EOF in Outer")
        }

        if tok.Kind == clawiter.TokenStructEnd {
            return nil
        }

        if tok.Kind != clawiter.TokenField {
            return fmt.Errorf("expected TokenField, got %v", tok.Kind)
        }

        switch tok.Name {
        case "Label":
            x.SetLabel(tok.String())
        case "Count":
            x.SetCount(tok.Int32())
        case "Nested":
            if tok.IsNil {
                continue
            }
            nested := NewInner(ctx)
            if err := nested.XXXIngestFrom(ctx, ts, opts); err != nil {
                return fmt.Errorf("ingesting Nested: %w", err)
            }
            x.SetNested(nested)
        default:
            if opts.IgnoreUnknownFields {
                if err := clawiter.SkipValue(ts, tok); err != nil {
                    return err
                }
                continue
            }
            return fmt.Errorf("unknown field: %s", tok.Name)
        }
    }
}

