// Code generated by "stringer -type=Type"; DO NOT EDIT.

package field

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FTUnknown-0]
	_ = x[FTBool-1]
	_ = x[FTInt8-2]
	_ = x[FTInt16-3]
	_ = x[FTInt32-4]
	_ = x[FTInt64-5]
	_ = x[FTUint8-6]
	_ = x[FTUint16-7]
	_ = x[FTUint32-8]
	_ = x[FTUint64-9]
	_ = x[FTFloat32-10]
	_ = x[FTFloat64-11]
	_ = x[FTString-12]
	_ = x[FTBytes-13]
	_ = x[FTStruct-14]
	_ = x[FTListBools-41]
	_ = x[FTListInt8-42]
	_ = x[FTListInt16-43]
	_ = x[FTListInt32-44]
	_ = x[FTListInt64-45]
	_ = x[FTListUint8-46]
	_ = x[FTListUint16-47]
	_ = x[FTListUint32-48]
	_ = x[FTListUint64-49]
	_ = x[FTListFloat32-50]
	_ = x[FTListFloat64-51]
	_ = x[FTListBytes-52]
	_ = x[FTListStrings-53]
	_ = x[FTListStructs-54]
}

const (
	_Type_name_0 = "FTUnknownFTBoolFTInt8FTInt16FTInt32FTInt64FTUint8FTUint16FTUint32FTUint64FTFloat32FTFloat64FTStringFTBytesFTStruct"
	_Type_name_1 = "FTListBoolsFTListInt8FTListInt16FTListInt32FTListInt64FTListUint8FTListUint16FTListUint32FTListUint64FTListFloat32FTListFloat64FTListBytesFTListStringsFTListStructs"
)

var (
	_Type_index_0 = [...]uint8{0, 9, 15, 21, 28, 35, 42, 49, 57, 65, 73, 82, 91, 99, 106, 114}
	_Type_index_1 = [...]uint8{0, 11, 21, 32, 43, 54, 65, 77, 89, 101, 114, 127, 138, 151, 164}
)

func (i Type) String() string {
	switch {
	case i <= 14:
		return _Type_name_0[_Type_index_0[i]:_Type_index_0[i+1]]
	case 41 <= i && i <= 54:
		i -= 41
		return _Type_name_1[_Type_index_1[i]:_Type_index_1[i+1]]
	default:
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
