// Code generated by "stringer -type=Type -linecomment"; DO NOT EDIT.

package errors

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeUnknown-0]
	_ = x[TypeBug-1]
	_ = x[TypeParameter-2]
	_ = x[TypeConn-3]
	_ = x[TypeTimeout-4]
	_ = x[TypeFS-5]
	_ = x[TypeStorageCreate-1000]
	_ = x[TypeStorageDelete-1001]
	_ = x[TypeStorageGet-1002]
	_ = x[TypeStorageList-1003]
	_ = x[TypeStorageUpdate-1004]
	_ = x[TypeStoragePut-1005]
	_ = x[TypeStorageClose-1006]
}

const (
	_Type_name_0 = "UnknownBugParameterConnTimeoutOrCancelFS"
	_Type_name_1 = "StorageCreateStorageDeleteStorageGetStorageListStorageUpdateStoragePutStorageClose"
)

var (
	_Type_index_0 = [...]uint8{0, 7, 10, 19, 23, 38, 40}
	_Type_index_1 = [...]uint8{0, 13, 26, 36, 47, 60, 70, 82}
)

func (i Type) String() string {
	switch {
	case i <= 5:
		return _Type_name_0[_Type_index_0[i]:_Type_index_0[i+1]]
	case 1000 <= i && i <= 1006:
		i -= 1000
		return _Type_name_1[_Type_index_1[i]:_Type_index_1[i+1]]
	default:
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
