// Code generated by "stringer -type=Category -linecomment"; DO NOT EDIT.

package errors

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CatUnknown-0]
	_ = x[Canceled-1]
	_ = x[ReservedUnknown-0]
	_ = x[InvalidArgument-3]
	_ = x[DeadlineExceeded-4]
	_ = x[NotFound-5]
	_ = x[AlreadyExists-6]
	_ = x[PermissionDenied-7]
	_ = x[ResourceExhausted-8]
	_ = x[FailedPrecondition-9]
	_ = x[Aborted-10]
	_ = x[OutOfRange-11]
	_ = x[Unimplemented-12]
	_ = x[Internal-13]
	_ = x[Unavailable-14]
	_ = x[DataLoss-15]
	_ = x[Unauthenticated-16]
}

const (
	_Category_name_0 = "UnknownCanceled"
	_Category_name_1 = "InvalidArgumentDeadlineExceededNotFoundAlreadyExistsPermissionDeniedResourceExhaustedFailedPreconditionAbortedOutOfRangeUnimplementedInternalUnavailableDataLossUnauthenticated"
)

var (
	_Category_index_0 = [...]uint8{0, 7, 15}
	_Category_index_1 = [...]uint8{0, 15, 31, 39, 52, 68, 85, 103, 110, 120, 133, 141, 152, 160, 175}
)

func (i Category) String() string {
	switch {
	case i <= 1:
		return _Category_name_0[_Category_index_0[i]:_Category_index_0[i+1]]
	case 3 <= i && i <= 16:
		i -= 3
		return _Category_name_1[_Category_index_1[i]:_Category_index_1[i+1]]
	default:
		return "Category(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
