// Package errors provides an errors package for this service. It includes all of the stdlib's
// functions and types.
package errors

import (
	"log/slog"

	"github.com/gostdlib/base/context"
	"github.com/gostdlib/base/errors"
)

//go:generate go tool github.com/johnsiilver/stringer -type=Category -linecomment

// Category represents the category of the error.
type Category uint32

func (c Category) Category() string {
	return c.String()
}

const (
	// CatUnknown represents an unknown category. This should not be used.
	CatUnknown Category = Category(0) // Unknown

	// Canceled indicates the operation was canceled (typically by the caller).
	//
	// The gRPC framework will generate this error code when cancellation
	// is requested.
	Canceled Category = 1

	// ReservedUnknown indicates that our error category is unknown. This is the grpc
	// error code for unknown, but we use 0 for this.  So they are the same. This should
	// not be used, use CatUnknown.
	ReservedUnknown Category = CatUnknown

	// InvalidArgument indicates client specified an invalid argument.
	// Note that this differs from FailedPrecondition. It indicates arguments
	// that are problematic regardless of the state of the system
	// (e.g., a malformed file name).
	//
	// This error code will not be generated by the gRPC framework.
	InvalidArgument Category = 3

	// DeadlineExceeded means operation expired before completion.
	// For operations that change the state of the system, this error may be
	// returned even if the operation has completed successfully. For
	// example, a successful response from a server could have been delayed
	// long enough for the deadline to expire.
	//
	// The gRPC framework will generate this error code when the deadline is
	// exceeded.
	DeadlineExceeded Category = 4

	// NotFound means some requested entity (e.g., file or directory) was
	// not found.
	//
	// This error code will not be generated by the gRPC framework.
	NotFound Category = 5

	// AlreadyExists means an attempt to create an entity failed because one
	// already exists.
	//
	// This error code will not be generated by the gRPC framework.
	AlreadyExists Category = 6

	// PermissionDenied indicates the caller does not have permission to
	// execute the specified operation. It must not be used for rejections
	// caused by exhausting some resource (use ResourceExhausted
	// instead for those errors). It must not be
	// used if the caller cannot be identified (use Unauthenticated
	// instead for those errors).
	//
	// This error code will not be generated by the gRPC core framework,
	// but expect authentication middleware to use it.
	PermissionDenied Category = 7

	// ResourceExhausted indicates some resource has been exhausted, perhaps
	// a per-user quota, or perhaps the entire file system is out of space.
	//
	// This error code will be generated by the gRPC framework in
	// out-of-memory and server overload situations, or when a message is
	// larger than the configured maximum size.
	ResourceExhausted Category = 8

	// FailedPrecondition indicates operation was rejected because the
	// system is not in a state required for the operation's execution.
	// For example, directory to be deleted may be non-empty, an rmdir
	// operation is applied to a non-directory, etc.
	//
	// A litmus test that may help a service implementor in deciding
	// between FailedPrecondition, Aborted, and Unavailable:
	//  (a) Use Unavailable if the client can retry just the failing call.
	//  (b) Use Aborted if the client should retry at a higher-level
	//      (e.g., restarting a read-modify-write sequence).
	//  (c) Use FailedPrecondition if the client should not retry until
	//      the system state has been explicitly fixed. E.g., if an "rmdir"
	//      fails because the directory is non-empty, FailedPrecondition
	//      should be returned since the client should not retry unless
	//      they have first fixed up the directory by deleting files from it.
	//  (d) Use FailedPrecondition if the client performs conditional
	//      REST Get/Update/Delete on a resource and the resource on the
	//      server does not match the condition. E.g., conflicting
	//      read-modify-write on the same resource.
	//
	// This error code will not be generated by the gRPC framework.
	FailedPrecondition Category = 9

	// Aborted indicates the operation was aborted, typically due to a
	// concurrency issue like sequencer check failures, transaction aborts,
	// etc.
	//
	// See litmus test above for deciding between FailedPrecondition,
	// Aborted, and Unavailable.
	//
	// This error code will not be generated by the gRPC framework.
	Aborted Category = 10

	// OutOfRange means operation was attempted past the valid range.
	// E.g., seeking or reading past end of file.
	//
	// Unlike InvalidArgument, this error indicates a problem that may
	// be fixed if the system state changes. For example, a 32-bit file
	// system will generate InvalidArgument if asked to read at an
	// offset that is not in the range [0,2^32-1], but it will generate
	// OutOfRange if asked to read from an offset past the current
	// file size.
	//
	// There is a fair bit of overlap between FailedPrecondition and
	// OutOfRange. We recommend using OutOfRange (the more specific
	// error) when it applies so that callers who are iterating through
	// a space can easily look for an OutOfRange error to detect when
	// they are done.
	//
	// This error code will not be generated by the gRPC framework.
	OutOfRange Category = 11

	// Unimplemented indicates operation is not implemented or not
	// supported/enabled in this service.
	//
	// This error code will be generated by the gRPC framework. Most
	// commonly, you will see this error code when a method implementation
	// is missing on the server. It can also be generated for unknown
	// compression algorithms or a disagreement as to whether an RPC should
	// be streaming.
	Unimplemented Category = 12

	// Internal errors. Means some invariants expected by underlying
	// system has been broken. If you see one of these errors,
	// something is very broken.
	//
	// This error code will be generated by the gRPC framework in several
	// internal error conditions.
	Internal Category = 13

	// Unavailable indicates the service is currently unavailable.
	// This is a most likely a transient condition and may be corrected
	// by retrying with a backoff. Note that it is not always safe to retry
	// non-idempotent operations.
	//
	// See litmus test above for deciding between FailedPrecondition,
	// Aborted, and Unavailable.
	//
	// This error code will be generated by the gRPC framework during
	// abrupt shutdown of a server process or network connection.
	Unavailable Category = 14

	// DataLoss indicates unrecoverable data loss or corruption.
	//
	// This error code will not be generated by the gRPC framework.
	DataLoss Category = 15

	// Unauthenticated indicates the request does not have valid
	// authentication credentials for the operation.
	//
	// The gRPC framework will generate this error code when the
	// authentication metadata is invalid or a Credentials callback fails,
	// but also expect authentication middleware to generate it.
	Unauthenticated Category = 16
	// ADD YOUR OWN CATEGORIES HERE
)

// LogAttrer is an interface that can be implemented by an error to return a list of attributes
// used in logging.
type LogAttrer = errors.LogAttrer

// Error is the error type for this service. Error implements github.com/gostdlib/base/errors.E .
type Error = errors.Error

// EOption is an optional argument for E().
type EOption = errors.EOption

// WithSuppressTraceErr will prevent the trace as being recorded with an error status.
// The trace will still receive the error message. This is useful for errors that are
// retried and you only want to get a status of error if the error is not resolved.
func WithSuppressTraceErr() EOption {
	return errors.WithSuppressTraceErr()
}

// WithCallNum is used if you need to set the runtime.CallNum() in order to get the correct filename and line.
// This can happen if you create a call wrapper around E(), because you would then need to look up one more stack frame
// for every wrapper. This defaults to 1 which sets to the frame of the caller of E().
func WithCallNum(i int) EOption {
	return errors.WithCallNum(i)
}

// WithStackTrace will add a stack trace to the error. This is useful for debugging in certain rare
// cases. This is not recommended for general use as it can cause performance issues when errors
// are created frequently.
func WithStackTrace() EOption {
	return errors.WithStackTrace()
}

// WithAttrs adds the given attributes to the error. These attributes will be included
// in logging output. This is in addition to any attributes that are in the Context.
func WithAttrs(attrs ...slog.Attr) EOption {
	return errors.WithAttrs(attrs...)
}

// RPCErr is an error from the rpc package.
type RPCErr struct {
	// Msg is the error message.
	Msg error
}

// Error returns the error message.
func (r RPCErr) Error() string {
	return r.Msg.Error()
}

// Is returns true if the target is an RPCErr type.
func (RPCErr) Is(target error) bool {
	if _, ok := target.(RPCErr); ok {
		return true
	}
	return false
}

// Unwrap unwraps the error.
func (r RPCErr) Unwrap() error {
	return r.Msg
}

// E creates a new Error with the given parameters. Every error will be of the RPCErr type.
// This allows for easy identification of errors that come from the rpc package.
func E(ctx context.Context, c errors.Category, msg error, options ...errors.EOption) Error {
	// This makes sure we do the correct call number since we are a wrapper. Now, if they set the
	// call number, this will not override it.
	opts := make([]errors.EOption, 0, len(options)+1)
	opts = append(opts, WithCallNum(2))
	opts = append(opts, options...)

	return errors.E(ctx, c, nil, RPCErr{msg}, opts...)
}
